Tweak docs
ManimCommunity/manim pull request #1036
Opened 2021-02-16 10:19 UTC by kolibril13

## Motivation:

This pr will make some further improvements in the docs (small tweaking of the example page)

## Acknowledgements
- [ x ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

2021-02-23 02:34 UTC, jsonvillanueva approved these changes

2021-02-23 02:34 UTC, jsonvillanueva commented on docs/source/examples.rst
> +            image.background_rectangle= SurroundingRectangle(image, GREEN)
```suggestion
            image.background_rectangle = SurroundingRectangle(image, GREEN)
```

2021-03-21 22:16 UTC, behackl commented
@kolibril13, what is the status of this PR? Are you still working on it? Should it be merged?

2021-03-21 23:31 UTC, kolibril13 commented
Yess, it can get merged.

2021-03-21 23:38 UTC, behackl requested changes
LGTM, apart from the scene name of the new example.

2021-03-21 23:38 UTC, behackl commented on docs/source/examples.rst
> +    class MovingGroupToDestiny(Scene):
```suggestion
.. manim:: MovingGroupToDestination

    class MovingGroupToDestination(Scene):
```

2021-03-21 23:54 UTC, behackl approved these changes

2021-03-21 23:55 UTC, merged