v0.4.0: prepare new release
ManimCommunity/manim pull request #1069
Opened 2021-03-03 02:24 UTC by eulertour

Prepare for v0.4.0 release.

As an aside, I think we're currently doing too much editing on the changelog. I'd consider the benefit of automating our releases to be greater than that of having an edited changelog.

2021-03-03 04:11 UTC, WampyCakes commented on docs/source/changelog.rst
> +- :pr:`984`: Add manim version to CLI output, append version name for generated gif+png, add version to metadata of rendered videos
```suggestion
- :pr:`984`: Add manim version to CLI output, append version name for generated gif+png, add version to metadata of rendered videos, change dark blue terminal text to default green
```

2021-03-03 04:15 UTC, WampyCakes commented
#981 will also need added to the changelog once it's merged

2021-03-03 06:05 UTC, naveen521kk approved these changes

2021-03-03 06:06 UTC, naveen521kk commented on docs/source/changelog.rst
> +- :pr:`1008`: ci: fix release asset upload
Shouldn't this be under other changes or something?

2021-03-03 06:25 UTC, jsonvillanueva approved these changes

2021-03-03 06:28 UTC, jsonvillanueva requested changes

2021-03-03 06:28 UTC, jsonvillanueva commented on docs/source/changelog.rst
> +
```suggestion
- :pr:`981`:  Bugfix: Fix WebGL renderer hot reload on Windows
```

2021-03-03 06:33 UTC, jsonvillanueva commented
> 
> As an aside, I think we're currently doing too much editing on the changelog. I'd consider the benefit of automating our releases to be greater than that of having an edited changelog.

Does this mean that the squash/merger needs better final commit message, or something more?

2021-03-03 08:46 UTC, behackl commented
Thank you for preparing the release!

> As an aside, I think we're currently doing too much editing on the changelog. I'd consider the benefit of automating our releases to be greater than that of having an edited changelog.

I disagree. I've been away for, like, 10 days or so -- and didn't get at all what some of the entries in the changelog actually mean. I consider myself somewhat involved when it comes to the community edition, but if the changelog doesn't let me easily get back to the current status, how is it going to help other users that are not that familiar with Manim?

This is why I like to put in the work of slightly editing the changelog. Stuff like including links helps a lot, and also replacing the often very unhelpful merge messages by the oneline summaries prepared by the PR authors helps to make changes more transparent and easier to understand.

As long as the people merging the PRs don't write the merge commit messages more careful, I don't see a way around someone having to go through the effort of editing the changelog manually.

I've now also done it for this changelog, but for some reason I am, once again, not allowed to push to your branch. Please use the latest commit from <https://github.com/behackl/manim/tree/prepare-v0.4.0>, which is <https://github.com/behackl/manim/commit/838f946fe01be35870087f249497970f7384abb5>.

2021-03-03 08:56 UTC, naveen521kk commented
I think `Rework of SVG engine` is missing.
A breaking change is missing https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release#breaking-changes

I remember I updated that wiki as and when I merged any PR, so having a look over there should be great.

2021-03-03 09:06 UTC, behackl commented
> I think `Rework of SVG engine` is missing.

915 is included in the list (although quite hidden...)

> A breaking change is missing https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release#breaking-changes
> 

In which PR was this introduced?

2021-03-03 09:10 UTC, naveen521kk commented
> In which PR was this introduced

In https://github.com/ManimCommunity/manim/pull/915

> 915 is included in the list (although quite hidden...)

I would say that should be the highlight of this version and should be visible...

2021-03-03 09:17 UTC, behackl commented
I agree. I've updated my branch: https://github.com/behackl/manim/commit/8225e1babe961104a6305a54d453107141bb03be

2021-03-03 19:28 UTC, WampyCakes commented
behackl@1ca0537 now @eulertour

2021-03-04 04:25 UTC, eulertour commented
Closing in favor of #1072

2021-03-04 04:25 UTC, closed without merging