Added 3D Mobjects: Dot3D and SmallDot3D
ManimCommunity/manim pull request #1097
Opened 2021-03-13 07:07 UTC by Darylgolden

## Motivation
To add spherical, three dimensional analogues of `Dot` and `SmallDot`.

## Overview / Explanation for Changes
Added 3D Mobjects: `Dot3D` and `SmallDot3D`

## Oneline Summary of Changes

```
- Added new feature ... / Fixed bug ... / ... (:pr:`PR NUMBER HERE`)
```

## Testing Status
Added tests for each Mobject. Tests pass locally.

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

2021-03-13 17:34 UTC, WampyCakes commented
I'm on board with adding a 3D Dot, though I think adding SmallDot3D is unnecessary. As the only difference between them is size and not shape, I think accepting the size in the constructor is sufficient. I'd also like to see a doc example, perhaps an image of a Dot3D on a set of axes? Otherwise, this looks good to me.

2021-03-13 23:50 UTC, Darylgolden commented
> 
> 
> I'm on board with adding a 3D Dot, though I think adding SmallDot3D is unnecessary. As the only difference between them is size and not shape, I think accepting the size in the constructor is sufficient. I'd also like to see a doc example, perhaps an image of a Dot3D on a set of axes? Otherwise, this looks good to me.

I agree, but I added SmallDot3D as an analogue to SmallDot. I can remove it if necessary.

2021-03-14 01:01 UTC, AntonBallmaier commented
I feel like resolution=(12, 24) is a bit overkill for a dot. Maybe reduce it to lower values.

2021-03-14 01:18 UTC, WampyCakes commented
> I agree, but I added SmallDot3D as an analogue to SmallDot. I can remove it if necessary.

I understand the reasoning, but what's the limiting factor? Should there also be a BigDot or an ExtraSmallDot? IMO dot is good enough

2021-03-14 02:00 UTC, Darylgolden commented
> 
> 
> > I agree, but I added SmallDot3D as an analogue to SmallDot. I can remove it if necessary.
> 
> I understand the reasoning, but what's the limiting factor? Should there also be a BigDot or an ExtraSmallDot? IMO dot is good enough

I understand, but to me it doesn't make sense to have `Dot` and `SmallDot` but only `Dot3D`. Either both `SmallDot` and `SmallDot3D` should be removed, or they should be both included.

2021-03-14 02:48 UTC, WampyCakes commented
SmallDot probably should be removed imo

2021-03-14 05:30 UTC, Darylgolden commented
Per the poll results in Discord, I have removed `SmallDot3D`. A separate PR should be made to remove `SmallDot` too.

2021-03-21 09:38 UTC, jsonvillanueva requested changes
Now that you can correctly render sphinx documentation, please have a look at our wiki on [documentation](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP)) for future documentation. It'd be helpful to have a code example using our manim directive, but this isn't strictly necessary.

2021-03-21 09:38 UTC, jsonvillanueva commented on manim/mobject/three_dimensions.py
> +    radius : :class:`float`
```suggestion
    radius : :class:`float`, optional
```

2021-03-21 09:38 UTC, jsonvillanueva commented on manim/mobject/three_dimensions.py
> +    """
```suggestion
    color : :class:`~.Colors`, optional
        The color of the :class:`Dot3D`
```

2021-03-24 09:01 UTC, jsonvillanueva approved these changes
LGTM! Although personally, I'm not too found of the name Dot3D, if it's what the community wants, then sure.

2021-03-24 09:05 UTC, Darylgolden commented
Hmm, any suggestions for alternative names then?

2021-03-24 09:11 UTC, jsonvillanueva commented
> 
> 
> Hmm, any suggestions for alternative names then?

Not really, it's just something I thought I'd mention. In plain English, a `Dot`, or "point", makes sense to be a *small* `Circle`... but you don't really call a *small* `Sphere` a "Dot3D". Other Spherical items include: balls, globes, orbs and well stars/suns if we're stretching the meaning of "perfect" Spheres, but aren't *that* good of options.

2021-03-24 17:13 UTC, WampyCakes commented
I agree with @jsonvillanueva, though I think the reasonable name choices are limited. As this is just a small sphere, if you were to name it `SmallSphere` it wouldn't even make sense to include. I think the upside to `Dot3D` is it captures the essence of its use.

2021-03-25 02:17 UTC, WampyCakes commented
I added an example of Dot3D and accidentally pushed it straight here. I meant to make a PR to your branch 😬

2021-03-25 02:19 UTC, WampyCakes commented
I went ahead and pushed the black update now though.

2021-03-25 02:44 UTC, WampyCakes approved these changes

2021-03-27 01:06 UTC, merged