Fixed broken t2c function in `Text` + refine docs of `Text`
ManimCommunity/manim pull request #1458
Opened 2021-05-03 15:58 UTC by kolibril13

now:
![image](https://user-images.githubusercontent.com/44469195/116900283-d95f9c80-ac38-11eb-9dfe-a767d3f0b8c6.png)
before:
"w" was still white, because white spaces were also counted as a character.
After this pr find_indexes can distinguish between cases that need to count white spaces, and those which don't.

2021-05-04 02:25 UTC, Darylgolden requested changes
LGTM, just minor things

2021-05-04 02:25 UTC, Darylgolden commented on manim/mobject/svg/text_mobject.py
> +                self.add(text0,text1,text2,text3,text4)
```suggestion
                self.add(text0, text1, text2, text3, text4)
```

2021-05-04 02:25 UTC, Darylgolden commented on manim/mobject/svg/text_mobject.py
>          """Internally used function. Sets colour for specified strings."""
```suggestion
        """Internally used function. Sets color for specified strings."""
```

2021-05-04 05:40 UTC, naveen521kk commented
@kolibril13 Can you give an example of what this fixes? I mean copy-pasting an example with screenshots of how it rendered before and after.

2021-05-04 05:48 UTC, naveen521kk commented
Also, can you try the coloring with `disable_ligature` flag?

2021-05-04 07:21 UTC, kolibril13 commented
![image](https://user-images.githubusercontent.com/44469195/116971534-01431480-acba-11eb-9fb2-d78e8820215a.png)
before this pr.
you can test it with:
`Text("Visit us at docs.manim.community",t2c={'docs.manim.community':YELLOW}).scale(1.3).shift(DOWN)`
on this branch, this is fixed.

2021-05-04 07:30 UTC, naveen521kk commented
It's because of ligatures and not spaces. Can you try disabling ligatures and then try?
```
Text("Visit us at docs.manim.community",t2c={'docs.manim.community':YELLOW}, disable_ligatures=True).scale(1.3).shift(DOWN)
```

2021-05-06 12:19 UTC, kolibril13 commented
releated to https://github.com/ManimCommunity/manim/issues/776

2021-05-06 12:36 UTC, kolibril13 commented
First image is from master, second image is from this branch.
So both is working: A) disable_ligatures and B) removing white spaces
![image](https://user-images.githubusercontent.com/44469195/117298964-4745d700-ae78-11eb-9c68-86e8fbb7cb8d.png)

2021-05-06 14:15 UTC, naveen521kk commented
This PR breaks colours even when `disable_ligatures` are on. For example,
```py
from manim import *


class a(Scene):
    def construct(self):
        a = Text(
            "Visit us at fl docs.manim.community",
            disable_ligatures=True,
            t2c={"docs.manim.community": YELLOW},
        )
        b = Text(
            "Visit us at fl docs.manim.community",
            disable_ligatures=False,
            t2c={"docs.manim.community": RED},
        )
        self.add(Group(a, b).arrange(DOWN))
```
render's as
![a_ManimCE_v0 6 0](https://user-images.githubusercontent.com/49693820/117313180-49715b00-aea3-11eb-8bcc-ba52d32e9395.png)

in this branch, while it renders as this in the master branch(which is expected.)
![bot](https://media.discordapp.net/attachments/780234936980078602/839867726150238248/scriptoutput.png?width=799&height=449)
which is expected one

2021-05-10 16:24 UTC, naveen521kk commented on manim/mobject/svg/text_mobject.py
> +                text6 = Text("Visit us at docs.manim.community",t2c={'docs.manim.community':YELLOW}, disable_ligatures=True).scale(1.3).shift(DOWN)
Also, chaining methods make the line so long that it's unreadable.

2021-05-10 17:42 UTC, naveen521kk commented on manim/mobject/svg/text_mobject.py
> +                    disable_ligatures=True)
Maybe?
```suggestion
                text6 = Text(
                    "Visit us at docs.manim.community",
                    t2c={"docs.manim.community": YELLOW},
                    disable_ligatures=True,
               )
```

2021-05-10 18:05 UTC, naveen521kk approved these changes
sgtm, will merge when ci passes

2021-05-10 19:44 UTC, merged