Example for `apply_complex_function`
ManimCommunity/manim pull request #1500
Opened 2021-05-12 14:44 UTC by kolibril13

2021-05-12 14:58 UTC, kolibril13 commented
> You should probably make this PR a draft for now :)

I think it is fixed now!

2021-05-12 15:14 UTC, AntonBallmaier commented
Docs reference: https://manimce--1500.org.readthedocs.build/en/1500/reference/manim.mobject.mobject.Mobject.html#manim.mobject.mobject.Mobject.apply_complex_function

2021-05-12 15:15 UTC, AntonBallmaier commented on manim/mobject/mobject.py
> +        ::manim ApplyFuncExample
```suggestion
        .. manim:: ApplyFuncExample
```

2021-05-14 10:35 UTC, PhotonSpheres approved these changes
LGTM

2021-05-23 09:20 UTC, Darylgolden requested changes
Some phrasing changes I think would be good.

2021-05-23 09:20 UTC, Darylgolden commented on manim/mobject/mobject.py
> +        """Complex function that is applied to the xy-plane
```suggestion
        """Applies a complex function to a :class:`Mobject`.
```

2021-05-23 09:20 UTC, Darylgolden commented on manim/mobject/mobject.py
> +        With z= u+iv  u respresents the x value, v represents the y value.
```suggestion
        The x and y coordinates correspond to the real and imaginary parts respectively.
```

2021-05-23 11:33 UTC, Darylgolden requested changes

2021-05-23 11:33 UTC, Darylgolden commented on manim/mobject/mobject.py
> +                    t=ValueTracker(0)
```suggestion
                    t = ValueTracker(0)
```

2021-05-23 15:01 UTC, Darylgolden approved these changes
LGTM

2021-05-23 16:58 UTC, merged