Allow playing Animations asynchronously using OpenGLRenderer
ManimCommunity/manim pull request #1528
Opened 2021-05-17 00:32 UTC by AntonBallmaier

## Changelog / Overview

`Scene.play` can take a new keyword argument `run_async`. If `True` this will start the animation and return to executing `Scene.construct` immediately. This feature is only availably using the `OpenGLRenderer`.

## Motivation
see #1488
closes #1267 

## Explanation for Changes

[Documentation Reference](https://manimce--1526.org.readthedocs.build/en/1526/reference/manim.scene.scene.Scene.html#manim.scene.scene.Scene.play)

## Testing Status

## Further Comments
I would like to add an example to the docs, but as far as I know we cannot render OpenGl-videos to the docs, right? 

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

2021-05-17 13:28 UTC, TRoboto commented
I've tried to play your example #1267, with preview enabled, after converting it to OpenGL, but it didn't work as it should. When I write to a file, I receive this error.
```py
ValueError: write to closed file
```

Find the scene below. Note that you should temporarily change [this line](https://github.com/ManimCommunity/manim/blob/e4bc0ea7d35404910904d4e73b365e278a57e839/manim/animation/indication.py#L258) to `lines = OpenGLVGroup()` in order for it to work.

```py
class UsingUpdater(Scene):
    def construct(self):
        # Setup
        dots = OpenGLVGroup(
            *[
                Dot(RIGHT * random.randrange(-6, 6) + UP * random.randrange(-2, 2))
                for i in range(10)
            ]
        )
        line = Line(UP * 3, DOWN * 3).align_on_border(LEFT)
        self.add(dots)
        self.play(Create(line))

        # Updater
        def flash_hit_dots(mob):
            for dot in dots:
                if dot.get_center()[0] < mob.get_center()[0] and not hasattr(
                    dot, "marked"
                ):
                    self.play(Flash(dot, run_time=0.5))
                    dot.marked = True

        line.add_updater(flash_hit_dots)

        # Animate Line
        self.play(line.animate.align_on_border(RIGHT), run_time=5)
        self.wait()
```

2021-05-17 14:23 UTC, AntonBallmaier commented
> I've tried to play your example #1267, with preview enabled, after converting it to OpenGL, but it didn't work as it should. When I write to a file, I receive this error.
> 
> ```python
> ValueError: write to closed file
> ```

That is the error that without the changes I made. Please make sure you are actually running the code on the branch of this PR. I just tested the same code and don't get that error.  

> 
> Find the scene below. Note that you should temporarily change [this line](https://github.com/ManimCommunity/manim/blob/e4bc0ea7d35404910904d4e73b365e278a57e839/manim/animation/indication.py#L258) to `lines = OpenGLVGroup()` in order for it to work.
> 
> ```python
> class UsingUpdater(Scene):
>     def construct(self):
>         # Setup
>         dots = OpenGLVGroup(
>             *[
>                 Dot(RIGHT * random.randrange(-6, 6) + UP * random.randrange(-2, 2))
>                 for i in range(10)
>             ]
>         )
>         line = Line(UP * 3, DOWN * 3).align_on_border(LEFT)
>         self.add(dots)
>         self.play(Create(line))
> 
>         # Updater
>         def flash_hit_dots(mob):
>             for dot in dots:
>                 if dot.get_center()[0] < mob.get_center()[0] and not hasattr(
>                     dot, "marked"
>                 ):
>                     self.play(Flash(dot, run_time=0.5))
>                     dot.marked = True
> 
>         line.add_updater(flash_hit_dots)
> 
>         # Animate Line
>         self.play(line.animate.align_on_border(RIGHT), run_time=5)
>         self.wait()
> ```

I tested the code and had to make a tiny adjustment for it to work:

```py
class UsingUpdater(Scene):
    def construct(self):
        # Setup
        dots = OpenGLVGroup(
            *[
                Dot(RIGHT * random.randrange(-6, 6) + UP * random.randrange(-2, 2))
                for i in range(10)
            ]
        )
        line = Line(UP * 3, DOWN * 3).align_on_border(LEFT)
        self.add(dots)

        # Updater
        def flash_hit_dots(mob):
            for dot in dots:
                if dot.get_center()[0] < line.get_center()[0] and not hasattr(
                    dot, "marked"
                ):
                    self.play(Flash(dot, run_time=0.5, rate_func=rush_from))
                    dot.marked = True

        line.add_updater(flash_hit_dots)

        # Animate Line
        self.play(line.animate.align_on_border(RIGHT), run_time=5)
        self.wait()

```

Resulting in:

https://user-images.githubusercontent.com/26899845/118504901-36288000-b72c-11eb-8c08-c560f057134b.mp4

2021-05-17 16:38 UTC, TRoboto commented
The old scene still doesn't work but with your edits, it does. When the `mob` argument is used inside the updater function, everything breaks. Is this supposed to happen?

2021-05-17 18:08 UTC, AntonBallmaier commented
> The old scene still doesn't work but with your edits, it does. When the `mob` argument is used inside the updater function, everything breaks. Is this supposed to happen?

Definitely not, and I will open an issue addressing that bug. It is however (as far as I can tell) not related to this PR.
Have a look at this:
```py
class AnimateBugTest(Scene):
    def construct(self):
        line = Line(UP * 3, DOWN * 3).align_on_border(LEFT)
        dot1 = Dot(color=RED)
        dot2 = Dot(color=GREEN)
        self.add(line, dot1, dot2)

        line.add_updater(lambda mob: dot1.move_to(mob))
        dot2.add_updater(lambda mob: mob.move_to(line))

        # Animate Line
        self.play(line.animate.align_on_border(RIGHT), run_time=5)
        self.wait()
```
No matter the renderer the result looks like this:

https://user-images.githubusercontent.com/26899845/118536063-8bc05500-b74b-11eb-9c20-a37478700f94.mp4

2021-05-17 20:39 UTC, TRoboto commented on manim/scene/scene.py
> +            The animations to be played. They are started at the same timed and played
timed is a typo here.

2021-05-17 20:47 UTC, TRoboto commented on manim/scene/scene.py
> +        self.sync_play_running = True
Is there a reason to set assign this variable here? Will I have to call wait for the async to work?

2021-05-17 20:50 UTC, TRoboto commented
> > The old scene still doesn't work but with your edits, it does. When the `mob` argument is used inside the updater function, everything breaks. Is this supposed to happen?
> 
> Definitely not, and I ~will open~ have opened an issue addressing that bug. It is however ~(as far as I can tell)~ (for sure) not related to this PR. See #1536 :) Thanks for the tip making me look into this +1

Thank you for the unstoppable contributions, your work is astonishing. I've added few comments for your consideration.

2021-05-17 20:53 UTC, TRoboto commented
> Definitely not, and I ~will open~ have opened an issue addressing that bug. It is however ~(as far as I can tell)~ (for sure) not related to this PR. See #1536 :) Thanks for the tip making me look into this +1

Thank you for the unstoppable contributions, your work is astonishing. This PR LGTM now.

2021-05-27 12:00 UTC, huguesdevimeux requested changes
So, that's a great addition. I left some comments. 
This crucially needs two things to my eyes : 
- Comments of the logic  ; there are parts that are kind of obscure and need explanation. 
- This needs test, I think both graphical and units. You could use mocks to test, I think. 

Aside, that's (again!) a great contribution !

2021-09-22 10:55 UTC, Darylgolden commented
Hi, can I check on the status of this PR?

2022-06-18 18:02 UTC, MrDiver commented
Closing this for now because there is no activity. We can come back to this. The issue is on the project board and the PR is linked!

2022-06-18 18:02 UTC, closed without merging