Add CLI/config for MSAA samples with OpenGL
ManimCommunity/manim pull request #1576
Opened 2021-05-26 05:14 UTC by charburgx

## Changelog / Overview

Add config `opengl_samples` for MSAA sampling in OpenGL rendering mode. Default value is 0.

## Motivation

3D surfaces are rendered with jagged edges, which is in contrast with the otherwise anti-aliased look of manim.

## Explanation for Changes

This gives users the option to specify the amount of MSAA sampling, allowing for smooth edges on 3D surfaces.

## Example Scene
Here is an example scene for demonstration purposes:

```
class ThreeDSurface(Scene):
    def construct(self):
        surface = OpenGLSurface(lambda u, v: [u, v, 1*(u**2 - v**2)], u_range=(-1, 1), v_range=(-1, 1), color=GREEN)
        surface.rotate(90 * DEGREES, axis=LEFT)
        surface.scale(2)

        self.add(surface)

        self.renderer.camera.set_phi(-30 * DEGREES)
        surface.add_updater(lambda x, dt: self.renderer.camera.rotate(30 * DEGREES * dt, axis=UP))

        self.wait(12)
```

Running with `--ogls=4` or `--ogls=0` will show the difference. (with `--renderer=opengl` of course!)

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Testing Status

Ran on Ubuntu 20.10 with a Geforce GTX 760. 

## Further Comments
This is unlikely to be compatible with integrated graphics.

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

2021-06-02 09:23 UTC, eulertour commented
I still plan to get to this, sorry for the wait

2021-06-03 04:23 UTC, eulertour approved these changes

2021-06-03 04:23 UTC, eulertour commented on manim/renderer/opengl_renderer.py
> +
Why copy the data from the antialiased frame buffer to the regular rather than just return it from the antialiased frame buffer directly?

2021-06-03 04:34 UTC, Darylgolden requested changes
Could you add a graphical unit test for this? Or is the rendering non-deterministic/different across systems?

2021-06-30 02:26 UTC, Darylgolden commented
Hi, can I check on the status of this PR?

2021-08-10 08:01 UTC, charburgx commented
@eulertour 
When I tried to directly use the MSAA buffer, the rendering broke. I believe the answer to why it is necessary to have two framebuffers is somewhere in [here](https://learnopengl.com/Advanced-OpenGL/Anti-Aliasing). Maybe this:

> Whenever we draw anything while the framebuffer object is bound, the rasterizer will take care of all the multisample operations. However, because a multisampled buffer is a bit special, we can't directly use the buffer for other operations like sampling it in a shader.

But I do not really know.

@Darylgolden 
I have added one graphical unit test which will not pass until #1887 is through. Whether or not it is system dependent I do not know, and will not know until I can run it on the workers.

2022-06-18 18:04 UTC, MrDiver commented
I think this might render itself useless after refactoring the OpenGL renderer. Closing this for now due to the conflicts and missing activity. Feel free to open a Discussion or join the ongoing discussion on refactoring.

2022-06-18 18:04 UTC, closed without merging