Reworked Example on :class:~.Polygon
ManimCommunity/manim pull request #1638
Opened 2021-06-05 19:09 UTC by peaceheis

## Changelog / Overview

Added a more detailed example for the Polygon Class

## Motivation

The previous example did not have as extensive showcasing of Polygon features.
## Explanation for Changes

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Testing Status

## Further Comments

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

2021-06-06 05:10 UTC, Nikhil0504 requested changes

2021-06-06 05:10 UTC, Nikhil0504 commented on manim/mobject/geometry.py
> +            self.add(isosceles, square, pentagon, rectangle, upright_rectangle)
Check the indentation again.

2021-06-06 07:05 UTC, naveen521kk requested changes
Can you follow the instructions in [#hackthon-guidelines](https://discord.com/channels/581738731934056449/846805485529464832/849962667568529428)? ie, use the manimator bot(`!mdocstring` command) to create doc strings.

2021-06-06 14:10 UTC, peaceheis commented
> Can you follow the instructions in [#hackthon-guidelines](https://discord.com/channels/581738731934056449/846805485529464832/849962667568529428)? ie, use the manimator bot(`!mdocstring` command) to create doc strings.

I did use the doc string command, Im not sure what went wrong..

2021-06-06 15:41 UTC, naveen521kk commented
> I did use the doc string command, Im not sure what went wrong..

You should paste that as it is.

2021-06-06 15:42 UTC, Nikhil0504 commented
> > Can you follow the instructions in [#hackthon-guidelines](https://discord.com/channels/581738731934056449/846805485529464832/849962667568529428)? ie, use the manimator bot(`!mdocstring` command) to create doc strings.
> 
> I did use the doc string command, Im not sure what went wrong..

You copy pasted it but only the first line is indented correctly, you should tab in the other lines as copy paste messes them up.

2021-06-09 04:49 UTC, hydrobeam commented
Tbh I prefer the old example more than this one. It feels less visually cluttered. I do realize that `Polygon` was under `Needs rework` for the hackathon, but I'm not sure in which direction it was intended for the example to go.

2021-06-10 01:46 UTC, peaceheis commented
> Tbh I prefer the old example more than this one. It feels less visually cluttered. I do realize that `Polygon` was under `Needs rework` for the hackathon, but I'm not sure in which direction it was intended for the example to go.

That's a fair assessment, I did err on the side of too much representation and not too little.

2021-06-21 07:27 UTC, hydrobeam commented
Closing this since there hasn't been a lot of activity and the current example is more clear as to what `Polygon` should do. Thank you for the effort nonetheless!

2021-06-21 07:27 UTC, closed without merging