Added example and parameter description to :class:'AnnularSector'
ManimCommunity/manim pull request #1685
Opened 2021-06-14 00:01 UTC by MathInvariance

## Changelog / Overview

## Motivation

## Explanation for Changes

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Testing Status

## Further Comments

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

2021-06-14 09:06 UTC, Nikhil0504 requested changes
Requested a few changes

2021-06-14 09:06 UTC, Nikhil0504 commented on manim/mobject/geometry.py
> +       The stroke width of the Annular Sector.
```suggestion
    inner_radius
       The inside radius of the Annular Sector.
    outer_radius
       The outside radius of the Annular Sector.
    angle
       The clockwise angle of the Annular Sector.
    start_angle
       The starting clockwise angle of the Annular Sector.
    fill_opacity
       The opacity of the color filled in the Annular Sector.
    stroke_width
       The stroke width of the Annular Sector.
```
The typings should be in the function parameters and not the docstrings.
See: https://docs.manim.community/en/latest/contributing/typings.html

2021-06-14 09:06 UTC, Nikhil0504 commented on manim/mobject/geometry.py
> +    color : optional
This should have a typehint `Color`

2021-06-14 09:06 UTC, Nikhil0504 commented on manim/mobject/geometry.py
> +                # Changed background color to clearly visualize changes in fill_opacity.
```suggestion
                # Changes background color to clearly visualize changes in fill_opacity.
```

2021-06-15 08:40 UTC, Nikhil0504 commented on manim/mobject/geometry.py
> +    color : optional
```suggestion
    color
```

2021-06-29 10:25 UTC, behackl approved these changes
LGTM, thanks for your contribution!

2021-06-29 10:26 UTC, merged