Updated imports in `geometry.py` and added example to :class:`~.Arrow`
ManimCommunity/manim pull request #1687
Opened 2021-06-14 05:26 UTC by MathInvariance

## Changelog / Overview

## Motivation

Added an example for `Arrow` that was approved during the hackathon. 
Additionally, upon the recommendation of @Darylgolden, I added import statements for `ArrowCircleFilledTip`, `ArrowCircleTip`, `ArrowSquareTip`, and `ArrowSquareFilledTip`. 
## Explanation for Changes

Previously, if someone wanted to change the shape of the tip for an `Arrow`, they would have to add the following import statement to their code `from manim.mobject.geometry import ArrowCircleFilledTip, ArrowCircleTip, ArrowSquareTip, ArrowSquareFilledTip`. Now, with adding these 4 classes to `__all__`, they will be imported with manim by default. Hence, with my proposed change, the previously mentioned import statement would no longer be required.
 

[Documentation Reference](https://manimce--####.org.readthedocs.build)

## Testing Status

## Further Comments

## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

2021-06-16 08:08 UTC, hydrobeam requested changes
I added several comments to reduce the line count of this example since the code looks very overwhelming at first. However, it is very visually impressive and I'm quite a fan.

2021-06-16 08:08 UTC, hydrobeam commented on manim/mobject/geometry.py
> +                v1 = VGroup()
Instead of having a comment, a better named variable would be more appropriate.
```suggestion
                left_group = VGroup()
```

2021-06-16 08:08 UTC, hydrobeam commented on manim/mobject/geometry.py
> +                v2 = VGroup()
Same as the previous comment.
```suggestion
                middle_group = VGroup()
```

2021-06-16 08:08 UTC, hydrobeam commented on manim/mobject/geometry.py
> +                v2.arrange_in_grid(cols=1)
```suggestion
                v2.arrange(DOWN)
```

2021-06-16 08:08 UTC, hydrobeam commented on manim/mobject/geometry.py
> +                v3 = VGroup()
```suggestion
                UR_group = VGroup()
```

2021-06-16 08:08 UTC, hydrobeam commented on manim/mobject/geometry.py
> +                v4 = VGroup()
```suggestion
                LR_group = VGroup()
```

2021-06-16 08:08 UTC, hydrobeam commented on manim/mobject/geometry.py
> +                v3.arrange_in_grid(cols=1)
```suggestion
                v3.arrange(DOWN)
```

2021-06-19 19:37 UTC, MathInvariance commented on manim/mobject/geometry.py
> +        class ArrowExample(Scene):
If you don't mind, I would like to keep the existing example as well. I don't want to get rid of someone else's work.

2021-06-19 19:41 UTC, MathInvariance commented on manim/mobject/geometry.py
> +        class ArrowExample(Scene):
If you don't mind, I would like to keep the existing example as well. I don't want to get rid of someone else's work.

2021-06-22 00:36 UTC, hydrobeam approved these changes
Some minor tweaks, but this LGTM 👏

2021-06-22 00:36 UTC, hydrobeam commented on manim/mobject/geometry.py
> +        class ArrowExample(Scene):
That's fair, it's actually my work so I wouldn't really mind 😆. Although, this example does address different concepts so I think it's fine if they're both up.

2021-06-22 00:36 UTC, hydrobeam commented on manim/mobject/geometry.py
> +                    left_group += Arrow(buff=i, start=2 * LEFT, end=2 * RIGHT)
A slightly more descriptive var name.
```suggestion
                for buff in np.arange(0, 2.2, 0.45):
                    left_group += Arrow(buff=buff, start=2 * LEFT, end=2 * RIGHT)
```

2021-06-22 00:36 UTC, hydrobeam commented on manim/mobject/geometry.py
> +                DR_group.arrange_in_grid(cols=1)
Forgot about this in my previous review.
```suggestion
                DR_group.arrange(DOWN)
```

2021-06-29 10:20 UTC, behackl approved these changes

2021-06-29 10:20 UTC, merged