docs: Added reference to VMobject.set_fill method
ManimCommunity/manim pull request #1749
Opened 2021-07-03 23:47 UTC by LedMeExplain

## Changelog / Overview
I'm new at contribuiting so I made a small change by adding reference to VMobject.set_fill method.

DO NOT REMOVE THE FOLLOWING CHANGELOG LINES, EVEN IF YOU DON'T USE THEM.-->

## Motivation
I've been using Manim for almost a month and I've realized that some useful methods are not documented, so I'll be working on that.

## Explanation for Changes
Explaining all of the methods in VMobject class will make Manim more attractive to general public to use it.

## Checklist
- [ x ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ x ] I have written a descriptive PR title (see top of PR template for examples)
- [ x ] I have written a changelog entry for the PR or deem it unnecessary
- [ x ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

2021-07-04 11:28 UTC, huguesdevimeux requested changes
SGTM, just a little thing missing 

Thanks for contributing !

2021-07-04 11:28 UTC, huguesdevimeux commented on manim/mobject/types/vectorized_mobject.py
> +
I think you forgot to mention the `return` statement

2021-07-04 14:53 UTC, LedMeExplain commented
Thanks for your time. I'm new at github so... How can I fix this? Do I need a to send a new pull request?

2021-07-04 19:01 UTC, LedMeExplain commented
@huguesdevimeux 
it's working fine
[VMobject.set_fill #1749](https://manimce--1749.org.readthedocs.build/en/1749/reference/manim.mobject.types.vectorized_mobject.VMobject.html#manim.mobject.types.vectorized_mobject.VMobject.set_fill)

2021-07-04 20:20 UTC, huguesdevimeux approved these changes

2021-07-04 20:20 UTC, huguesdevimeux commented
> Thanks for your time. I'm new at github so... How can I fix this? Do I need a to send a new pull request?

I see that you figured it out. SGTM, thanks for the contribution :D

2021-07-06 09:32 UTC, behackl approved these changes
Looks good to me in general, left a few comments! Please address them, then this can be merged.

2021-07-06 09:32 UTC, behackl commented on manim/mobject/types/vectorized_mobject.py
> +        including its subMobjects.
The second part about the submobjects depends on the ``family`` parameter and should be mentioned separately.

```suggestion
        """Set the fill color and fill opacity of a :class:`VMobject`.
```

2021-07-06 09:32 UTC, behackl commented on manim/mobject/types/vectorized_mobject.py
> +            Fill opacity of the :class:`VMobject`.
If you want to add type hints, please add them to the function header (`def set_fill(self, color=None, opacity: float = None, family: bool = True):`). Also, here is a suggestion for a short description for the third parameter:

```suggestion
        color
            Fill color of the :class:`VMobject`.
        opacity
            Fill opacity of the :class:`VMobject`.
        family
            If ``True``, the fill color of all submobjects is also set.
```

2021-07-06 09:32 UTC, behackl commented on manim/mobject/types/vectorized_mobject.py
> +            All Mobjects are initialized with 0 fill_opacity. If you forget to set it, the fill color won't show.
There is currently movement regarding this behavior (see #1714), I'd suggest to remove this block here and deal with a clarification of the situation in #1714.

2021-07-08 13:17 UTC, LedMeExplain commented
It's perfect 👍

2021-07-08 13:21 UTC, behackl approved these changes

2021-07-08 13:21 UTC, merged