Add non-inplace operator overloads to :class:`~.ValueTracker`
ManimCommunity/manim pull request #1855
Opened 2021-08-02 10:49 UTC by kilacoda

## Changelog / Overview

Added methods `__add__`, `__sub__`, `__floordiv__`, `__mul__`, `__truediv__`, `__mod__`, `__pow__`, `__radd__`, `__rmul__` to :class:`~.ValueTracker`

## Explanation for Changes

Adds operator overrides for non-inplace operations to provide more flexibility in the use of ValueTrackers.

## Documentation Reference
 
https://docs.manim.community/en/stable/reference/manim.mobject.value_tracker.ValueTracker.html

## Testing Status

Tested with `pytest test_value_tracker.py`, 23/23 tests pass
## Further Comments

N/A
## Checklist
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [ ] I have written a descriptive PR title (see top of PR template for examples)
- [ ] I have written a changelog entry for the PR or deem it unnecessary
- [ ] My new functions/classes either have a docstring or are private
- [ ] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [ ] The PR title is descriptive enough
- [ ] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

2021-08-05 08:15 UTC, PhotonSpheres commented
Just curios, why the change in the of Sphinx `docs/requirements.txt` here? Doesn't seem to be related to the PR, no?

2021-08-05 10:48 UTC, kilacoda commented
It wasn't my doing, must have come along when I was updating the branch.

2021-08-05 11:44 UTC, Darylgolden commented
I updated the branch from GH and they're successfully removed.

2021-08-08 06:02 UTC, Darylgolden requested changes
Minor typehint changes, otherwise LGTM!

2021-08-08 06:02 UTC, Darylgolden commented on manim/mobject/value_tracker.py
> +    def __add__(self, value: Union[int, float]):
```suggestion
    def __add__(self, value: float):
```

2021-08-08 06:02 UTC, Darylgolden commented on manim/mobject/value_tracker.py
> +    def __add__(self, value: Union[int, float]):
We've previously discussed and agreed that just using `float` as the typehint is fine.

2021-08-08 06:02 UTC, Darylgolden commented on manim/mobject/value_tracker.py
> +    def __floordiv__(self, d_value: Union[int, float]):
```suggestion
    def __floordiv__(self, d_value: float):
```

2021-08-15 02:05 UTC, hydrobeam commented
If `__add__`  (and the rest) is defined and the implementations for `__add__` and `__iadd__` are the same, wouldn't it be more convenient to just drop the `__iadd__`'s since it falls back to `__add__`? From the python docs:

> For instance, if x is an instance of a class with an `__iadd__()` method, `x += y` is equivalent to `x = x.__iadd__(y)` . Otherwise, `x.__add__(y)` and `y.__radd__(x)` are considered,

https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types

2022-01-14 05:45 UTC, Darylgolden commented
Hi, are you still planning on working on this?

2022-01-30 16:00 UTC, behackl commented
Closing this due to inactivity. Please re-open in case you want to continue working on this. The docstrings currently don't look right to me.

2022-01-30 16:00 UTC, closed without merging