Fixed wobbly Rotate animation
ManimCommunity/manim pull request #1938
Opened 2021-08-20 13:39 UTC by sparshg

## Overview:

Fixed Rotation animation when trying to rotate by multiples of 2π
Closes #1935 

## Explanation

Multiples of 2π didn't work because the start and end position \*almost\* coincides, so path function wasn't completely accurate, and interpolation was wobbly, wrote custom `path_func` for rotation animation to fix

https://user-images.githubusercontent.com/43041139/130240719-57127feb-1792-4f24-8996-d9f2d343d206.mp4

https://user-images.githubusercontent.com/43041139/130240662-d8512e97-8e6f-417e-a7f9-fe629552efd6.mp4

 

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2021-08-20 13:44 UTC, sparshg commented
well that was an annoying bug ever since I started using manim lol, never noticed it only happens at multiples of 2π

2021-08-20 13:59 UTC, behackl commented
See my comment about this in #1935, I think it would be better to fix the underlying issue with `path_arc`.

2021-08-20 14:03 UTC, sparshg commented
I saw that, but that cannot be fixed because that function takes the start and end point only and generates an arc, which is not possible if both points coincide, (because radius cannot be known). Here tho we know the radius so thats why I think writing custom function is better.

2021-08-20 14:12 UTC, sparshg commented
hmmmm ook lemme try

2021-08-20 16:00 UTC, sparshg commented
ok so I tried this, seems better imo

2021-08-20 16:06 UTC, sparshg commented
ok so how about this

2021-08-20 22:56 UTC, behackl requested changes
Looks good to me. Could you add an animated graphical unit test (see `tests/test_graphical_units/test_transform.py` for examples how this should look) for a scene that has four squares that rotate (in the same play call) by -4pi, -2pi, 2pi, 4pi?

Apart from the missing test, this is good to go from my point of view.

2021-08-20 22:56 UTC, behackl commented on manim/animation/transform.py
> +            self._path_arc, self.path_arc_axis, self.path_arc_centers
I have a (slight) preference for passing keyword arguments as actual keyword arguments.

```suggestion
            self._path_arc,
            axis=self.path_arc_axis,
            arc_centers=self.path_arc_centers
```

2021-08-21 10:42 UTC, behackl approved these changes
Looks good to me! Thanks for fixing this.

2021-08-21 13:00 UTC, merged