Fix the problem of text index in class Text
ManimCommunity/manim pull request #1977
Opened 2021-08-30 02:27 UTC by xia0long

## Overview: What does this pull request change?

use self.original_text or self.text depending on the situation.

## Motivation and Explanation: Why and how do your changes improve the library?

Fix the bug of indexing error.

## Links to added or changed documentation pages
 

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2021-08-30 08:23 UTC, ryanmccauley211 commented
Thanks for raising this, can you add a code snippet to replicate the error and maybe a bit more detail on what the indexing error is for anyone who is unfamiliar with it please?

2021-08-30 10:05 UTC, xia0long commented
> Thanks for raising this, can you add a code snippet to replicate the error and maybe a bit more detail on what the indexing error is for anyone who is unfamiliar with it please?

Hi @ryanmccauley211 !
I added some descriptions, feel free to contact me if u have any further infomation.

2021-08-30 10:17 UTC, ryanmccauley211 requested changes
It works well for me with the example you give and fixes the index issue, but it seems to ignore coloring when spaces are added. For example:

```py
class Test(Scene):
    def construct(self):
        t = Text("Cherry Blossoms in Spring",
            disable_ligatures=False,
            t2c={"Cherry Blossoms": RED, "Spring": GREEN}
        ).scale(1)

        self.add(t)
```

currently results in the broken indexing but adds color to both words:

<img width="849" alt="Screenshot 2021-08-30 at 11 13 02" src="https://user-images.githubusercontent.com/32387857/131324382-054abe3e-60a2-4569-bce7-e7a6720e6c69.png">

With your change it doesn't seem to add any color:

<img width="848" alt="Screenshot 2021-08-30 at 11 16 26" src="https://user-images.githubusercontent.com/32387857/131324492-3a9e9897-e7b3-4b3e-89e8-135c64f2eab8.png">

2021-08-30 13:55 UTC, WampyCakes commented
Since it seems that our text indexing has had numerous problems, would you mind adding a test to ensure we catch this should any future problems arise?

2021-08-30 14:00 UTC, hydrobeam commented
I'm not actually sure we can properly test `Text` right now since the default font it uses varies based on operating system. Maybe you can get around that by specifying a font shared across the OS's we test?

2021-08-30 14:14 UTC, xia0long commented
@WampyCakes 

No problem, I'll add a basic test which we can improve in the future.

2021-09-01 03:31 UTC, xia0long commented
When I wrote the test case, It seems that the `color` attribute in `Text` can't get the correct value, so I use `get_color()` instead.

```py
In [3]: text = Text("Hello World", t2c={"Hello": RED})

In [4]: text.color
Out[4]: <Color white>

In [5]: text.submobjects[1].color
Out[5]: <Color white>

In [6]: text.submobjects[1].get_color()
Out[6]: <Color #fc6255>
```

2021-09-01 15:49 UTC, xia0long reviewed
fixed

2021-09-01 17:59 UTC, ryanmccauley211 reviewed
It is working really well now thank you! It seems to have failed the build though, once that is resolved I think it looks good to approve

2021-09-02 02:36 UTC, xia0long commented on manim/mobject/svg/text_mobject.py
> +        return [[i.start(), i.start() + len(word)] for i in re.finditer(word, text)]
Hi @naveen521kk! Thank you for your feedback, can you give an example of this problem?

2021-09-02 05:06 UTC, naveen521kk commented on manim/mobject/svg/text_mobject.py
> +        return [[i.start(), i.start() + len(word)] for i in re.finditer(word, text)]
Something like this
```py
class a(Scene):
  def construct(self):
    self.add(Text('hello', t2c={'[2:4]':RED}))
```
should work.

2021-09-02 06:01 UTC, xia0long commented on manim/mobject/svg/text_mobject.py
> +        return [[i.start(), i.start() + len(word)] for i in re.finditer(word, text)]
This approach does help with long string coloring, but putting slices in this position is odd and can be problematic in some cases.

**Code**
```py
class Test(Scene):
    def construct(self):
        t = Text("hello [:2]", 
            disable_ligatures=False, 
            t2c={"[:2]": YELLOW, "o": RED}
        ).scale(1)

        self.add(t)
```
![Test_ManimCE_v0 10 0](https://user-images.githubusercontent.com/8436021/131790056-baf74239-2148-4081-9d15-0c2fb125b42f.jpg)

2021-09-02 06:42 UTC, xia0long commented on manim/mobject/svg/text_mobject.py
> +        return [[i.start(), i.start() + len(word)] for i in re.finditer(word, text)]
When a long string needs to be colored, I think the approach blow is more appropriate.
```py
class Test(Scene):
    def construct(self):
        text_string = "Long string"
        self.add(Text(text_string, t2c={text_string[:3]:RED}))
```

2021-09-03 04:54 UTC, xia0long commented
> It works well for me with the example you give and fixes the index issue, but it seems to ignore coloring when spaces are added. For example:
> 
> ```python
> class Test(Scene):
>     def construct(self):
>         t = Text("Cherry Blossoms in Spring",
>             disable_ligatures=False,
>             t2c={"Cherry Blossoms": RED, "Spring": GREEN}
>         ).scale(1)
> 
>         self.add(t)
> ```
> 
> currently results in the broken indexing but adds color to both words:
> 
> <img alt="Screenshot 2021-08-30 at 11 13 02" width="849" src="https://user-images.githubusercontent.com/32387857/131324382-054abe3e-60a2-4569-bce7-e7a6720e6c69.png">
> 
> With your change it doesn't seem to add any color:
> 
> <img alt="Screenshot 2021-08-30 at 11 16 26" width="848" src="https://user-images.githubusercontent.com/32387857/131324492-3a9e9897-e7b3-4b3e-89e8-135c64f2eab8.png">

Hi @ryanmccauley211, thanks for your review! and these requested changes are outdated.

2021-09-03 05:07 UTC, naveen521kk commented on manim/mobject/svg/text_mobject.py
> +        return [[i.start(), i.start() + len(word)] for i in re.finditer(word, text)]
You would need to document them and also in changelog.

2021-09-10 06:01 UTC, xia0long commented on manim/mobject/svg/text_mobject.py
> +        return [[i.start(), i.start() + len(word)] for i in re.finditer(word, text)]
Sorry for the delayed response! I have made some changes,  feel free to contact me if you have any further information.

2021-09-26 10:02 UTC, ryanmccauley211 commented
@xia0long @naveen521kk Is there anything still outstanding in this PR? The docs are still failing though so that needs fixed before we can merge it.

2021-09-26 13:22 UTC, naveen521kk commented
This PR removes support for indexes in `t2c` as described https://github.com/ManimCommunity/manim/pull/1977#discussion_r700460673. I don't like to break that feature (or atleast make a clear discussion with others before breaking it).

2021-09-27 10:51 UTC, xia0long commented
The reason for removing support for indexes I've written [here](https://github.com/ManimCommunity/manim/pull/1977#discussion_r700769448), perhaps we can discuss whether there is a better way to fix this problem.

2021-09-28 17:25 UTC, ryanmccauley211 commented
> The reason for removing support for indexes I've written [here](https://github.com/ManimCommunity/manim/pull/1977#discussion_r700769448), perhaps we can discuss whether there is a better way to fix this problem.

Ah sorry I didn't realise the indexing part was still an issue. Yea I agree with naveen that we should try to find a fix that doesn't remove the option to use indexes

2022-01-08 03:52 UTC, closed without merging