Implement implicit graphing
ManimCommunity/manim pull request #2094
Opened 2021-09-28 06:43 UTC by icedcoffeeee

## Overview: What does this pull request change?

* Added new :class:`~.ImplicitFunction` mobject 
* Added new :meth:`.CoordinateSystem.get_implicit_graph`

This is a direct continuation of #2046 , my fork went missing.
## Motivation and Explanation: Why and how do your changes improve the library?

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2021-09-28 07:11 UTC, Darylgolden requested changes
Some more suggestions, in addition to the ones in the previous PR.

2021-09-28 07:11 UTC, Darylgolden commented on manim/mobject/coordinate_systems.py
> +            The color of the graph
```suggestion
            The color of the graph.
```

2021-09-28 07:11 UTC, Darylgolden commented on manim/mobject/functions.py
> +        points = [np.pad(i, [(0, 0), (0, 1)]) for i in points if i != []]
Perhaps `point_lists` is a better variable name?

2021-09-28 07:11 UTC, Darylgolden commented on manim/mobject/functions.py
> +        for p in points:
I think "for list in point_lists" is more descriptive.

2021-09-28 07:11 UTC, Darylgolden commented on manim/mobject/functions.py
> +from manim.mobject.geometry import Line
This is now unused, please remove.

2021-09-28 08:18 UTC, Darylgolden approved these changes
LGTM! Maybe the number of quads could use some tuning depending on the whether we want to prioritize speed or accuracy, but that's just a minor point.

2021-09-28 13:14 UTC, PhotonSpheres commented
A small nitpick of mine would be that `graph` doesn't seem to be the accurate term, no? I think this would be called curve or something similar. But I understand that graph might be more user-friendly.

2021-09-28 16:25 UTC, icedcoffeeee commented
> I think this would be called curve or something similar. 

@PhotonSpheres 
I don' t mind changing the method name to `.get_implicit_curve` is that's preferred.

2021-09-28 20:09 UTC, PhotonSpheres commented
> @PhotonSpheres I don't mind changing the method name to `.get_implicit_curve` if that's preferred.

Not sure if I even prefer that, just wanted to mention that.

2021-09-28 23:50 UTC, Darylgolden commented
If there's no clear preference, I think it's up to you @icedcoffeeee

2021-09-29 01:47 UTC, Darylgolden requested changes

2021-09-29 01:47 UTC, Darylgolden commented on manim/mobject/coordinate_systems.py
> +    def get_implicit_graph(
`use_smoothing` should be a parameter here too.

2021-09-29 01:47 UTC, Darylgolden commented
I tried changing the `min_depth` and `max_quads` and there doesn't seem to be any noticeable difference in quality or speed, strange...

2021-09-29 03:38 UTC, icedcoffeeee commented
> there's no clear preference, I think it's up to you

After googling the term implicit graph, which brings up something totally different, I'll change it to curve.

> changing the min_depth and max_quads and there doesn't seem to be any noticeable difference in quality or speed

Ah, that's something I forgot to mention in the docs. The depth is technically also the number of quads, where quads = 2 ^ depth. The higher value between them is taken into calculation.

2021-09-29 07:35 UTC, behackl commented
> If there's no clear preference, I think it's up to you @icedcoffeeee

Given that creating a "normal plot" is done via `get_graph`, one could make an argument for `get_implicit_graph`, but generally I also prefer `get_implicit_curve` or `get_implicit_plot`.

(Actually I also don't like that all of these start with `get`, but well, that is another story.)

I think it is fine the way it is now, anyways.

2021-09-29 22:38 UTC, Darylgolden approved these changes

2021-09-30 15:31 UTC, behackl requested changes
LGTM, only have very minor change requests.

2021-09-30 15:31 UTC, behackl commented on manim/mobject/functions.py
> +            A small min depth means that some small details might
```suggestion
            A small ``min_depth`` :math:`d` means that some small details might
```

2021-09-30 15:31 UTC, behackl commented on manim/mobject/functions.py
> +            (4 ^ min depth) uniform quads.
```suggestion
            :math:`4^d` uniform quads.
```

2021-09-30 15:31 UTC, behackl commented on manim/mobject/functions.py
> +            The value of max quads strongly correspond to the
```suggestion
            The value of ``max_quads`` strongly corresponds to the
```

2021-09-30 15:31 UTC, behackl commented on manim/mobject/functions.py
> +            self.max_quads,
As above: please pass as keyword arguments.

2021-10-01 04:57 UTC, hydrobeam reviewed
This PR pretty much LGTM, but I left some nitpicky comments.

Although, testing with the opengl renderer, there's some weird artefacting going on, at least on my machine. I've attached videos with the two types of shaders. Projection shaders don't seem to have the same issue.

Default shaders:
https://user-images.githubusercontent.com/70682032/135565364-eaebc7e7-3e06-4b58-9134-883f3325ca86.mp4

Projection Shaders:
https://user-images.githubusercontent.com/70682032/135565289-14b6cb36-2c38-47bf-bb1f-cf555bbc639a.mp4

2021-10-01 05:21 UTC, icedcoffeeee commented on manim/mobject/coordinate_systems.py
> +        color: Color = WHITE,
It was initially pointed out by @Darylgolden in https://github.com/ManimCommunity/manim/pull/2094#discussion_r718086821
But if the idea is to make it more parallel with `.get_graph` implementation, should min_depth and max_quads be omitted too?

2021-10-01 05:29 UTC, icedcoffeeee commented
> testing with the opengl renderer, there's some weird artefacting going on, at least on my machine

This is very odd. I don't get any artifacts at all with both shaders.

https://user-images.githubusercontent.com/83535735/135569903-63bd8747-6094-40d9-8ff8-7368a4c6809a.mp4

Maybe it's gfx card specific, but that doesn't make perfect sense.

2021-10-01 09:23 UTC, icedcoffeeee commented
@hydrobeam Apparently the neater import caused a timeout for the docs. I'll revert the commit for now.

2021-10-01 09:25 UTC, behackl commented
> @hydrobeam Apparently the neater import caused a timeout for the docs. I'll revert the commit for now.

Not sure this is related.

2021-10-01 09:26 UTC, icedcoffeeee commented
> Not sure this is related.

Oh? I'm not sure what else.. 🤔

2021-10-02 00:02 UTC, behackl approved these changes
The changes look good to me, thank you! There is a minor change conflict, could you resolve it and then run `poetry lock` and commit the resulting changes to the lockfile?

2021-10-02 06:58 UTC, merged