Added OpenGL compatibility to `ThreeDScene.add_fixed_orientation_mobjects` and  `ThreeDScene.add_fixed_in_frame_mobjects`
ManimCommunity/manim pull request #2158
Opened 2021-10-05 10:23 UTC by icedcoffeeee

## Overview: What does this pull request change?

## Motivation and Explanation: Why and how do your changes improve the library?

I appended updaters on each mobject to face the camera in each frame. This also works in interactive mode.

Code used:
```py
class FixOrientation(ThreeDScene):
    def construct(self):
        ax = ThreeDAxes((-3, 3), (-3, 3), (-3, 3), 6, 6, 6)
        ax_labels = ax.get_axis_labels()
        ax_labels.add(ax.get_z_axis_label("z").rotate(-PI / 2, RIGHT))
        vect = Vector([1, 2, 3], color=BLUE)
        vect2 = Vector([-2, 0, 1], color=YELLOW)
        coord_label = vect.coordinate_label(n_dim=3, color=BLUE)
        coord_label2 = vect2.coordinate_label(n_dim=3, color=YELLOW)
        self.add(ax, vect, vect2)
        self.add_fixed_orientation_mobjects(*ax_labels, coord_label, coord_label2)
        self.set_camera_orientation(PI / 3, PI / 4)
        self.begin_ambient_camera_rotation(0.5)
        self.wait(5)
```
Output of `--write_to_movie`:

https://user-images.githubusercontent.com/83535735/136005462-735e7e43-4488-43af-b397-2df00d9454f7.mp4

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2021-10-09 08:01 UTC, ryanmccauley211 submitted a review, later dismissed
Works well for me ! Thanks for this, I left some comments and requests for tests if possible

2022-02-11 10:55 UTC, behackl requested changes
This looks good to me in general, thank you! I have one concern regarding the naming of `mob_center`, see below.

There is some funny behavior with `fixed_orientation_mobject` and the way the stroke is rendered relative to the camera orientation, see these two screenshots:

![image](https://user-images.githubusercontent.com/11851593/153579142-03fbdfe9-a8f3-4214-87ef-371e21d6cd66.png)

![image](https://user-images.githubusercontent.com/11851593/153579188-7f007302-2584-4786-9f65-7b464d72ccd0.png)

I don't think this should block merging this though. We can just open an issue and document the behavior to be fixed eventually.

2022-02-11 10:55 UTC, behackl commented on manim/mobject/opengl_mobject.py
> +    mob_center = _Uniforms()  # for fixed orientation reference
I think for the sake of clarity it would make sense to rename `mob_center` to something more explicit like `fixed_mobject_center` or `fixed_center`.

2022-02-11 11:41 UTC, icedcoffeeee commented
> There is some funny behavior with fixed_orientation_mobject and the way the stroke is rendered relative to the camera orientation, see these two screenshots:

This is something I also noticed. Unfortunately, I don't have any insight on how to solve this.

> I don't think this should block merging this though. We can just open an issue and document the behavior to be fixed eventually.

That sounds good to me

2022-02-11 11:48 UTC, behackl commented on manim/grpc/impl/frame_server_impl.py
> +        mob_proto.image_mobject_data.center.z = fixed_orientation_center[2]
This might have been unintentional :-)

2022-02-11 12:03 UTC, icedcoffeeee commented on manim/grpc/impl/frame_server_impl.py
> +        mob_proto.image_mobject_data.center.z = fixed_orientation_center[2]
Oops, yup, and fixed :)

2022-02-11 13:14 UTC, behackl approved these changes

2022-02-12 08:47 UTC, merged