Fixed mistakes in building_blocks
ManimCommunity/manim pull request #2230
Opened 2021-10-25 14:57 UTC by mostlyaman

## Overview: What does this pull request change?

Checked `building_blocks.rst`. Also pushing changes for other files, if I find any mistakes.

## Motivation and Explanation: Why and how do your changes improve the library?

## Links to added or changed documentation pages

## Further Information and Comments

Closes #1401

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2021-11-20 07:48 UTC, Darylgolden commented
Hi, is this ready for review?

2021-11-20 07:56 UTC, mostlyaman commented
Hi, I apologise I have taken so much time, I have been busy and could not take time out to complete this PR. I suppose it's best for this PR to get reviewed and merged for now.

2021-11-20 08:00 UTC, Darylgolden requested changes

2021-11-20 08:00 UTC, Darylgolden commented on docs/source/tutorials/building_blocks.rst
> +So, the logic of calculating the number to display at each step will be; 50 + alpha * (100 - 50).
I don't think semicolon is correct here. Leaving out the punctuation and formatting the formula as a code literal will probably be best.

2021-11-20 09:17 UTC, Darylgolden approved these changes
Thanks, this LGTM!

2021-11-21 04:11 UTC, lucasricci approved these changes
LGTM

2021-11-27 14:55 UTC, merged