Add support for in-place medication operators
ManimCommunity/manim pull request #2311
Opened 2021-11-20 01:49 UTC by peaceheis

This deals with issue #2275, "Operator overloading for Mobject "Integer"

## Overview: What does this pull request change?

This adds support for DecimalNumber to use in place modification operators, as a shorthand for the set_value() method. Support for the equivalent operators that do not modify in-place was NOT added. This is a response to issue #2275 

## Motivation and Explanation: Why and how do your changes improve the library?

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2021-11-20 16:03 UTC, behackl requested changes
Thank you for your contribution! The implementation looks fine to me, and operator overloading for `DecimalNumber` does make sense semantically to me, so I support this change.

It would be good to add a test for these methods, could you please have a look at `tests/test_numbers.py` and add a test there to make sure that we don't accidentally break this?

2021-11-20 17:08 UTC, peaceheis commented
I can do that! Should each test be in a separate function or can they all be in one?

2021-11-20 18:31 UTC, peaceheis commented
I don't think putting it into different functions was necessary, so I put it all into one - I haven't written tests before, did I do it correctly?

2021-11-20 18:32 UTC, hydrobeam commented
Tbh I'm not a big fan of adding these operators. It feels odd to use an operator when all you're doing is applying a function.

2021-11-20 18:34 UTC, peaceheis commented
> Tbh I'm not a big fan of adding these operators. It feels odd to use an operator when all you're doing is applying a function.

I mean, DeicmalNumber is really just a layer over an int, so being able to treat it like such isn't really a problem is it? It's mostly just syntactic sugar

2022-01-31 10:14 UTC, Darylgolden commented
I also don't like adding operators directly to DecimalNumber. I think what can make using DecimalNumber more convenient is would be changing `value` to a property so that it can be modified like a normal attribute: `self.value += 3` for example.

2022-06-18 19:45 UTC, MrDiver commented
Should we keep this around? I put it on the to be closed list. Feel free to move it to the discussions tab instead.

2022-07-06 00:43 UTC, closed without merging