Refactored :class:`~.BarChart` and made it inherit from :class:`~.Axes`.
ManimCommunity/manim pull request #2387
Opened 2021-12-20 07:23 UTC by hydrobeam

## Overview: What does this pull request change?

- :class:`~.BarChart` now inherits from :class:`~.Axes`, allowing it to use `Axes`' methods. Also improves `BarChart`'s configuration and ease of use.
- Added :meth:`~.BarChart.add_bar_labels` to annotate each bar of a :class:`

## Motivation and Explanation: Why and how do your changes improve the library?

This PR is a continuation of the PR started by @LedMeExplain in #1916. The PR was inactive for a while, so I decided to implement the suggestions I had left, clean up the code + add documentation. See #1916 for a more full description of the changes, but here are some of the changes that I made when taking it over:

- removed `get_bar_labels` method in favour of just using built in `add_labels` for a `NumberLine`.
- Removed uncessary parameters that could just be initialized via `axis_config/x_axis_config/y_axis_config`.
    - `y_label_buff`
    - `x_label_scale_value`
    - `y_number_scale`
    - `x_label_buff`
    - `y_include_numbers`.
  
- Removed `y_step` and merged its capabilities with `y_range` 
- Renamed `bar_buff` to `bar_width`. (same functionality, just that bigger number = bigger bar, not smaller bar)
- Removed getter methods in favour of directly accessing attributes via the axes.
- Adjusted `get_bar_labels` (returns mobs) into `add_bar_labels` (just adds them).
 

## Links to added or changed documentation pages

Waiting to render...

## Further Information and Comments

I'll add some tests soon if there's no objection to the changes in this PR.

Also, this is technically a breaking change, not sure if just breaking it is fine or if we should go into some deprecation period. (I favour just breaking it since `BarChart` isn't too commonly used).

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2021-12-25 03:22 UTC, hydrobeam commented
Managed to fix it with the latest commit.

2021-12-25 04:39 UTC, icedcoffeeee requested changes
Two concerns:
1. The previous implementation had `.change_bar_values`, maybe add it here too?
2. Can you add tests? It turns out it hasn't been tested before.

Other than that, everything else LGTM

2021-12-26 01:41 UTC, hydrobeam commented
I've written tests (adapted from @LedMeExplain's showcase in the original PR) and fixed negative bar values + rewrote some examples.

2021-12-30 23:01 UTC, hydrobeam commented
Merged #2397  into this PR to remove the need for the `x_label_constructor` parameter.

2021-12-31 04:37 UTC, Darylgolden reviewed
I think `BarChart` is better placed on `coordinate_systems.py` rather than `probability.py`. What do you think?

2021-12-31 04:39 UTC, GameDungeon commented
Honestly, why don't we just delete probability.py?

2021-12-31 04:39 UTC, Darylgolden commented
> Honestly, why don't we just delete probability.py?

That was what I was getting at.

2021-12-31 04:52 UTC, hydrobeam commented
> I think BarChart is better placed on coordinate_systems.py rather than probability.py. What do you think?

I disagree, it's not an essential component of graphing and is more of an auxillary class for displaying data.

> Honestly, why don't we just delete probability.py?

I think it's reasonable to have at least one supported way of showing data in Manim. Before this PR the class was essentially an unusable mess, but with these changes it's much more sensible and belongs in the library. As for `SampleSpace`, I'm indifferent. It has a poor implementation and is not nearly as ubiquitous as a bar chart.

2022-01-06 12:50 UTC, behackl approved these changes
This seems like useful improvements. I'm fine with merging this.

2022-01-06 12:55 UTC, icedcoffeeee approved these changes
LGTM, thank you for the improvements :)

2022-01-16 09:44 UTC, hydrobeam commented on manim/mobject/probability.py
> +        """Annotates each bar with its corresponding value. Use `self.bar_labels` to access the
```suggestion
        """Annotates each bar with its corresponding value. Use ``self.bar_labels`` to access the
```

2022-01-16 14:05 UTC, merged