Added `about_point` for :class:`~ApplyMatrix`
ManimCommunity/manim pull request #2388
Opened 2021-12-20 07:45 UTC by lanpai

## Overview: What does this pull request change?

:class:`~ApplyMatrix` now has optional kwarg `about_point` in its `__init__` method.

## Motivation and Explanation: Why and how do your changes improve the library?

It allows for the animation to be much more robust and useful for different scenarios.

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2021-12-20 07:56 UTC, hydrobeam requested changes
Thank you for the contribution! I left a brief suggestion on its implementation.

Could you also add a brief description of the parameter ([see here for instructions](https://docs.manim.community/en/stable/contributing/docstrings.html)) and a quick test for it in `test_transform.py`? [See here](https://docs.manim.community/en/stable/contributing/testing.html) for how to add a test. Let me know if you have any questions 👍

2021-12-20 07:56 UTC, hydrobeam commented on manim/animation/transform.py
> +        about_point = kwargs["about_point"]
I feel like this may be better suited as a parameter.

2021-12-20 19:54 UTC, lanpai commented
> Thank you for the contribution! I left a brief suggestion on its implementation.
> 
> Could you also add a brief description of the parameter ([see here for instructions](https://docs.manim.community/en/stable/contributing/docstrings.html)) and a quick test for it in `test_transform.py`? [See here](https://docs.manim.community/en/stable/contributing/testing.html) for how to add a test. Let me know if you have any questions 👍

`about_point` is now a parameter with relevant descriptions and tests implemented :+1:

2021-12-25 05:19 UTC, hydrobeam approved these changes
I added a quick unit test to compare it against `rotate`'s about_point, but LGTM!

2021-12-25 05:37 UTC, hydrobeam commented on tests/test_transform.py
> +    np.testing.assert_array_equal(square_1.points.all() == square_2.points.all())
```suggestion
    np.testing.assert_array_equal(square_1.points, square_2.points)
```

2021-12-31 00:10 UTC, behackl approved these changes
Thanks for your contribution, just added some minor docstring formatting suggestions. Will apply them myself and then merge this.

2021-12-31 00:10 UTC, behackl commented on manim/animation/transform.py
> +    """Applies a matrix transform to an mobject
```suggestion
    """Applies a matrix transform to an mobject.
```

2021-12-31 00:10 UTC, behackl commented on manim/animation/transform.py
> +        The matrix transform
```suggestion
        The transformation matrix.
```

2021-12-31 00:10 UTC, behackl commented on manim/animation/transform.py
> +        The origin point for the transform. Defaults to ORIGIN
```suggestion
        The origin point for the transform. Defaults to ``ORIGIN``.
```

2021-12-31 00:14 UTC, merged