Fix animations introducing or removing objects
ManimCommunity/manim pull request #2396
Opened 2021-12-25 02:14 UTC by marcin-serwin

## Overview: What does this pull request change?

* `ShowPassingFlash` now removes objects when the animation is finished
* Added `remover` flag to `Animation` analogous to `remover`

## Motivation and Explanation: Why and how do your changes improve the library?

Fixes #2349.

Code:
```python
class IntroducersInSuccession(Scene):
    def construct(self):
        mobjs = [Square() for _ in range(11)]
        VGroup(*mobjs[:6]).arrange().shift(2 * UP)
        VGroup(*mobjs[6:]).arrange().shift(2 * DOWN)
        self.play(
            Succession(
                Circumscribe(mobjs[0]),
                ShowSubmobjectsOneByOne(mobjs[1]),
                Create(mobjs[2]),
                FadeIn(mobjs[3]),
                Write(mobjs[4]),
                Unwrite(mobjs[5]),
                GrowFromCenter(mobjs[6]),
                ShowPassingFlash(mobjs[7]),
                SpinInFromNothing(mobjs[8]),
                FadeOut(mobjs[9]),
                DrawBorderThenFill(mobjs[10]),
            )
        )
```

## Links to added or changed documentation pages

## Further Information and Comments

Before:

https://user-images.githubusercontent.com/12128106/147375936-0072cf39-ac79-4c46-9211-9c6dcd76544c.mp4

After:

https://user-images.githubusercontent.com/12128106/147375926-0ff6a60d-6cda-4186-bbeb-575556a04405.mp4

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2021-12-31 01:24 UTC, behackl commented
I like the semantics of this approach! In particular, the new method for preparing the scene seems useful. I'll have to think a bit more about this and how it interacts with the already present machinery for adding mobjects (the `moving_mobjects` and the `Scene.add_mobjects_from_animations` stuff), but in general this looks very clean.

For now, thank you!

2022-01-06 18:09 UTC, behackl approved these changes
Overall, I like these changes – thanks again for your efforts! There are some things I am somewhat unhappy with (like the fact that this makes it less easy to understand when in an Animation's life cycle mobjects are added to the scene), but I think the fact that this PR makes Animations more symmetric with the `introducer` keyword arg on the one hand, and the `setup_scene` method on the other hand, outweighs my concerns.

It would be good to have another dev look over this / approve it before it is merged.

2022-01-07 10:33 UTC, marcin-serwin commented on manim/animation/composition.py
> +        self.scene = None
I think this was needed only because some tests didn't call `setup_scene` before begin. I've updated them and it's no longer necessary.

2022-01-19 13:01 UTC, Darylgolden requested changes
LGTM in general, just some questions and comments.

2022-01-19 13:01 UTC, Darylgolden commented on manim/mobject/graph.py
> +    ) -> Tuple[Hashable, np.ndarray, dict, "Mobject"]:
Typehint, see above

2022-01-19 13:01 UTC, Darylgolden commented on manim/mobject/graph.py
> +        vertex_mobject: "Mobject",
Typehints, see above

2022-01-20 16:26 UTC, marcin-serwin commented on manim/animation/animation.py
> +    def is_introducer(self) -> bool:
It's made this way to mirror the `is_remover` method.

2022-01-22 00:29 UTC, Darylgolden approved these changes
LGTM, thank you!

2022-01-23 01:56 UTC, merged