Adding "from __future__ import annotations" imports
ManimCommunity/manim pull request #2429
Opened 2022-01-06 21:04 UTC by GameDungeon

## Overview: What does this pull request change?
First, all code in the pull request was written by automated processes.
I believe that importing from animations will have great benefits for our typing efforts. 

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-01-09 10:11 UTC, Darylgolden approved these changes
I like the new syntax, and if everything is done via `pyupgrade` I don't think there is really a risk of breaking anything. For the sake of the changelog and other reviewers, can you be more explicit on what exactly the changes made here were?

2022-01-09 20:48 UTC, GameDungeon commented
This better?

2022-01-09 21:07 UTC, hydrobeam commented
What are the specific features that this adds? What changes does this make to how types are written? What does `from __future__ import annotations` actually do?  Could you provide more explanation about the motivation, consequences etc... 

It feels like there's a lot of information that we're missing here.

2022-01-09 21:08 UTC, GameDungeon commented
The real issue with that is I would have to rewrite several peps to explain everything.

2022-01-09 21:33 UTC, hydrobeam commented
I don't think explaining the changes in your PR and why you made them amounts to "rewriting several peps".

2022-01-09 21:34 UTC, GameDungeon commented
Well, the changes I made are. I told isort to add "from __future__ import annotations" to the top of every python file. Then pyupgrade upgraded them to the new sytanx.

2022-01-15 02:49 UTC, GameDungeon commented
It seems to me the only thing holding this back is the change description. I honestly don't know what needs to be put, so I'll leave that to anyone else that wants a shot at it.

2022-01-20 02:57 UTC, Darylgolden requested changes

2022-01-20 02:57 UTC, Darylgolden commented on example_scenes/advanced_tex_fonts.py
> +from __future__ import annotations
I don't think example scenes should have the import. Please remove them from all example scenes.

2022-01-20 03:02 UTC, GameDungeon reviewed
Fixed the example scenes.

2022-01-20 03:02 UTC, GameDungeon commented on example_scenes/basic.py
> +from __future__ import annotations
```suggestion
```

2022-01-20 03:02 UTC, GameDungeon commented on example_scenes/customtex.py
> +from __future__ import annotations
```suggestion
```

2022-01-20 03:02 UTC, GameDungeon commented on example_scenes/opengl.py
> +from __future__ import annotations
```suggestion
```

2022-01-20 04:25 UTC, Darylgolden approved these changes
I think this LGTM, the unnecessary imports can be removed in a separate PR.

2022-01-20 04:26 UTC, merged