Changed example in Surface.set_fill_by_value()
ManimCommunity/manim pull request #2431
Opened 2022-01-06 23:03 UTC by Leo-Torch

## Overview: What does this pull request change?

This changes the example in the set_fill_by_value() method.

## Motivation and Explanation: Why and how do your changes improve the library?

This change makes it easier for new users to understand how to use the method.
## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-01-07 15:14 UTC, behackl commented
Hello! Thank you for your contribution!

Can you please explain, in how far your changes make the method easier to use? I somehow prefer the look and feel of the current example.

2022-01-07 17:49 UTC, Leo-Torch commented
> Hello! Thank you for your contribution!
> 
> Can you please explain, in how far your changes make the method easier to use? I somehow prefer the look and feel of the current example.

In the original example, I didn't feel that it effectively illustrated the `FillByValue` gradient very clearly to people who are planning the use the method. Only a small streak of yellow can be seen on the graph with a large portion of the coloring being green. By making the gradient more varied it becomes clear how you can use the method, and what you can expect to see from it.

2022-01-07 18:34 UTC, behackl commented
So, here is the original version: <https://docs.manim.community/en/stable/reference/manim.mobject.three_dimensions.Surface.html>, and here is the version from your PR: <https://manimce--2431.org.readthedocs.build/en/2431/reference/manim.mobject.three_dimensions.Surface.html>

The aim of the original example is to have a gradient along the z-axis, with large function values being green and small ones being red. Semantically, I slightly prefer that over setting the gradient along the y-axis. But I definitely agree with you: the example could be much better! Do you think changing the camera orientation to make the valleys and mountains of the function more visible would help?

2022-01-07 18:43 UTC, Leo-Torch commented
I definitely agree. I'll make a new commit with a better camera orientation for the z-axis shortly.

2022-01-10 10:57 UTC, behackl requested changes
Looks good to me, thank you! I have one minor suggestion with respect to formatting, but otherwise this can be merged. Please leave a comment or request a review when you have applied the changes!

2022-01-10 10:57 UTC, behackl commented on manim/mobject/three_dimensions.py
> +                    surface_plane.set_fill_by_value(axes=axes, colors=[(RED, -0.5), (YELLOW, 0), (GREEN, 0.5)], axis = 2)
Minor formatting change.

```suggestion
                    surface_plane.set_fill_by_value(axes=axes, colors=[(RED, -0.5), (YELLOW, 0), (GREEN, 0.5)], axis=2)
```

2022-01-29 16:29 UTC, Darylgolden approved these changes

2022-01-29 16:29 UTC, merged