Fixing gif related issues
ManimCommunity/manim pull request #2477
Opened 2022-01-21 09:10 UTC by Kiran-Raj-Dev

## Overview
For some odd reason the file name for gifs had the manim version at the end, which led to a 
`The file path\of\file.gif does not exist` error because `file_ops.py` didn't know that that was done. 

I have removed that addition of the version name , alternatively we could add the version name in to preview as well, that's a matter of preference I guess.

## Addendum
Apparently `brew install ffmpeg` installs `ffplay` as well so we aren't adding anything additional anyway.
Ignore the part where I say that in the commit message for `file_ops.py`

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-01-21 09:39 UTC, Kiran-Raj-Dev commented
So, the gif paths must have the version? 🤔

2022-01-21 09:54 UTC, Darylgolden commented
> So, the gif paths must have the version? 🤔

No, they don't have to. That's how it was, and the CI just checks that it hasn't changed. I've always found it odd that gif files had a different naming convention as other output files, and think it makes sense to standardize the naming. You'd just have to modify the control data in the tests so that they pass.

2022-01-21 09:57 UTC, Kiran-Raj-Dev commented
Whoops, I just made changes to make the tests happy 😓 
Should, I revert?

2022-01-21 10:38 UTC, Kiran-Raj-Dev commented
Something doesn't feel right in the logs.
```py
AssertionError: gif file not found at 
"/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/popen-gw1/test_gif_format_output0/videos/simple_scenes/480p15/SquareToCircle_ManimCE_v0.14.0.gif"
117
E       assert False
118
E        +  where False = <bound method Path.exists of PosixPath('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/popen-gw1/test_gif_format_output0/videos/simple_scenes/480p15/SquareToCircle_ManimCE_v0.14.0.gif')>()
119
E        +    where <bound method Path.exists of PosixPath('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/popen-gw1/test_gif_format_output0/videos/simple_scenes/480p15/SquareToCircle_ManimCE_v0.14.0.gif')> = PosixPath('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/popen-gw1/test_gif_format_output0/videos/simple_scenes/480p15/SquareToCircle_ManimCE_v0.14.0.gif').exists

```
The paths are correct and they do have the extension so why does it say not found?

2022-01-25 10:45 UTC, behackl requested changes
The changes in `file_ops` are fine as MacOS's default behavior when opening gifs is questionable at best.

I don't think simply stripping the version from the file name is a good solution though. As it stands, mp4 and more complex movie files have the version set in the metadata, but for gifs this is also not the case. This would mean that there is different behavior for png (for which the file name is still modified), gif and proper movie files.

Why does the mechanism work correctly for rendering pngs? The control flow for gifs should just mirror that one.

2022-01-25 10:52 UTC, Kiran-Raj-Dev commented
Right so you're saying that the version number should retain?

2022-01-25 11:03 UTC, behackl commented
> Right so you're saying that the version number should retain?

I think that would be at least consistent with the decision made in #984. We can ask in the community whether we should keep the names like that at all, but for this PR the file output behavior should be kept as-is. :-)

2022-01-25 12:26 UTC, Kiran-Raj-Dev commented
I don't know where things broke. 
I will close this and open a new PR.
Sorry for the mess.

2022-01-25 12:26 UTC, closed without merging