Added guide on profiling and improving performance
ManimCommunity/manim pull request #2517
Opened 2022-01-31 04:45 UTC by Darylgolden

## Overview: What does this pull request change?

## Motivation and Explanation: Why and how do your changes improve the library?

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-01-31 09:11 UTC, behackl requested changes
Image is not loaded, but other than that LGTM. Thanks for putting this together!

2022-01-31 09:11 UTC, behackl commented on docs/source/contributing/performance.rst
> +.. image:: _static/snakeviz.png
Image is not loaded correctly. One of these two fixes it (I think), not sure whether the first one works.

```suggestion
.. image:: /_static/snakeviz.png
```

```suggestion
.. image:: ../_static/snakeviz.png
```

2022-02-02 11:56 UTC, behackl commented
Draft?

2022-02-02 12:08 UTC, Darylgolden commented
> Draft?

Yeah, a code block isn't rendering for some reason.

2022-02-02 12:14 UTC, behackl commented on docs/source/contributing/performance.rst
> +    from manim import *
(Some?) Directives require a newline between them and their content.

```suggestion

    from manim import *
```

2022-02-02 23:10 UTC, behackl approved these changes
LGTM now!

2022-02-02 23:12 UTC, merged