Improved Error in :mod:`.utils.tex_file_writing`
ManimCommunity/manim pull request #2574
Opened 2022-02-25 11:00 UTC by Kiran-Raj-Dev

## Overview: What does this pull request change?
This removes the infamous `max() arg is an empty sequence` error
Added an insight for when a package is not installed
Fixes #2360

## Further Information and Comments

I am not sure if
> Install it using your LaTeX package manager

is a helpful enough insight. Suggestions Welcome!

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-02-25 11:04 UTC, Darylgolden commented on manim/utils/tex_file_writing.py
> +    yield f"You do not have package {match[1]} installed"
```suggestion
    yield f"You do not have package {match[1]} installed."
```

2022-02-25 11:04 UTC, Darylgolden commented on manim/utils/tex_file_writing.py
> +    yield "Install it using your LaTeX package manager"
```suggestion
    yield "Install it using your LaTeX package manager."
```

2022-02-25 11:05 UTC, Darylgolden requested changes
Thank you! Can you add tests that assert the correct error messages are raised?

2022-02-25 11:11 UTC, Kiran-Raj-Dev commented
Sure!

2022-02-25 15:58 UTC, Kiran-Raj-Dev commented
I sank in enough time, but I have no idea why the logs will not be produced even after passing in the `--log_to_file` parameter.

2022-02-26 06:13 UTC, Kiran-Raj-Dev commented
Insights are logged as INFO not ERROR.
Here the verbosity is set to ERROR. Since you asked:
> Can you add tests that assert the correct error messages are raised?

Setting it to INFO will include the insights

2022-02-26 06:16 UTC, Darylgolden commented
I think it'll be good to test that the insight is raised.

2022-02-26 08:14 UTC, Darylgolden requested changes

2022-02-26 08:14 UTC, Darylgolden commented on manim/utils/tex_file_writing.py
> +    yield f"Install {matching[1]} it using your LaTeX package manager, or check for typos"
```suggestion
    yield f"Install {matching[1]} it using your LaTeX package manager, or check for typos."
```

2022-02-26 11:32 UTC, Darylgolden approved these changes
Thank you, LGTM!

2022-02-26 19:50 UTC, merged

2022-02-28 22:32 UTC, behackl commented
This unfortunately broke rendering of TeX strings containing `%`. Trying to create `Tex(r"\%")` fails in v0.15.0.