Fix incorrect typehint for Text class's color property
ManimCommunity/manim pull request #2578
Opened 2022-02-26 03:16 UTC by yzhong52

## Overview: What does this pull request change?

The type should be str instead of color. If we check line 475 how it is used:

```
color = Color(color) if color else VMobject().color
```

The color class is created there.

## Motivation and Explanation: Why and how do your changes improve the library?

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [x] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-02-26 08:15 UTC, Darylgolden requested changes
Thank you for your contribution! The type should be both `Color` and `str`; the user may choose to pass a `Color` class as an argument.

2022-02-26 14:43 UTC, yzhong52 commented
Not sure if I agree with that @Darylgolden. Color is being used as string everywhere I can see: 

https://docs.manim.community/en/stable/examples.html

Same as here, it is just an error in the type hint. The implementation below is also expecting `color` to be a string. 

If we do want to add support for a strong `Color` type in the public facing APIs, it should probably be a wider effort to change them all (as well as the documentation) instead of just this `Text` class here?

2022-02-28 13:00 UTC, yzhong52 commented
> That's true, such efforts have already started [as seen here](https://github.com/ManimCommunity/manim/blame/main/manim/mobject/geometry/arc.py#L483). Most of the time, these incorrect typehints are overlooked by reviewers reviewing the PRs introducing them, which explains the inconsistencies.

That sounds great! Can we merge this? I ran into issue using color for Text here and I just don't want others to run into the same bug. I am happy to close this for now too to avoid conflicts with the broader effort.

2022-02-28 14:40 UTC, behackl submitted a review, later dismissed

2022-02-28 14:40 UTC, behackl commented on manim/mobject/text/text_mobject.py
> +        color: str | None = None,
The type hint should still include `Color`.

```suggestion
        color: Color | str | None = None,
```

2022-02-28 20:30 UTC, Darylgolden commented
To elaborate, something like `Color(Color(RED)) ` works perfectly fine.

2022-03-01 11:53 UTC, yzhong52 commented
> To elaborate, something like Color(Color(RED)) works perfectly fine.

Thanks for clarifying. Didn't know it works this way!

2022-03-02 11:27 UTC, Darylgolden approved these changes
LGTM, thank you!

2022-03-02 11:28 UTC, merged