support groups in `TransformMatchingParts`
ManimCommunity/manim pull request #2602
Opened 2022-03-07 12:15 UTC by NicoWeio

## Overview: What does this pull request change?

## Motivation and Explanation: Why and how do your changes improve the library?
I was looking for an elegant way to update an equation, letting some variables “fly in” from elsewhere.
`TransformMatchingTex` is great, but it only supported one `MathTex`-like input and one output.

This PR adds support for `Group`s (and `VGroup`s) by accessing their individual `submobject`s. 
I made it recursive, so that nested groups are supported.
Mobjects that are neither groups, nor contain a `tex_string` will still raise an Exception.

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-03-07 13:49 UTC, NicoWeio commented
I wonder if the example in 6c6cd90 is good enough. One might consider integrating the previous example (without groups) or creating a second one.
In fact, I already did No. 1:

```python
class MatchingEquationParts(Scene):
    def construct(self):
        variables = VGroup(MathTex("a"), MathTex("b"), MathTex("c")).arrange_submobjects().shift(UP)

        eq1 = MathTex("{{x}}^2", "+", "{{y}}^2", "=", "{{z}}^2")
        eq2 = MathTex("{{a}}^2", "+", "{{b}}^2", "=", "{{c}}^2")
        eq3 = MathTex("{{a}}^2", "=", "{{c}}^2", "-", "{{b}}^2")

        self.add(eq1)
        self.wait(0.5)
        self.play(TransformMatchingTex(Group(eq1, variables), eq2))
        self.wait(0.5)
        self.play(TransformMatchingTex(eq2, eq3))
        self.wait(0.5)
```

2022-03-07 17:41 UTC, Kiran-Raj-Dev commented
I think having some form of splitting is nice then no control.
This is certainly a change for the better!

2022-03-08 08:22 UTC, behackl requested changes
Thank you for your contribution, this looks good and almost ready to merge to me!

I've left a request for a minor change, please take a look.

2022-03-08 08:22 UTC, behackl commented on manim/animation/transform_matching_parts.py
> +        if isinstance(mobject, (Group, VGroup)):
mobject should also be allowed to be an `OpenGLGroup` or an `OpenGLVGroup`.

2022-03-08 09:35 UTC, behackl approved these changes
Thank you!

2022-03-08 09:38 UTC, merged