Deprecate color enum usage and change constants from ``str` to type `Color`
ManimCommunity/manim pull request #2606
Opened 2022-03-09 13:26 UTC by BrorSebastianSjovald

## Overview: What does this pull request change?

This PR improves the color handling by deprecating uses of the Colors class and replace usage of the Enums with color constants as specified in https://github.com/ManimCommunity/manim/issues/2451 . At this point, a deprecation warning is raised when trying to use the Colors class using `manim.utils.deprecation`.

## Motivation and Explanation: Why and how do your changes improve the library?

The overall goal is to simplify the use of color by standardizing the approach as stated in https://github.com/ManimCommunity/manim/issues/2451 . By deprecating the use of the Enums and providing a way of using the constants in a similar way, we're creating a standard for how colors should be used.

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-03-21 07:24 UTC, Darylgolden requested changes
Thank you for your work! Other than some minor typehint problems, I think this is good to go.

2022-03-21 07:24 UTC, Darylgolden commented on manim/mobject/geometry/shape_matchers.py
> +        color: str | None = None,
```suggestion
        color: Color | str | None = None,
```

2022-03-21 07:24 UTC, Darylgolden commented on manim/mobject/geometry/shape_matchers.py
> +        color: str | None = None,
Pretty sure that a color object would work fine here too.

2022-03-21 07:24 UTC, Darylgolden commented on manim/mobject/mobject.py
> +        self, color: str = None, opacity: float = 0.75, **kwargs
```suggestion
        self, color: Color | str | None = None, opacity: float = 0.75, **kwargs
```

2022-04-15 19:56 UTC, behackl commented
@BrorSebastianSjovald @ludwigjo any updates here?

2022-06-18 20:19 UTC, MrDiver commented
Closing this for now. Making Colors the main source of truth again with exporting constants shouldn't break anything. `colour.py` has just too many duplicated features to our own implementation.

2022-06-18 20:19 UTC, closed without merging