Copyedited Documentation
ManimCommunity/manim pull request #2640
Opened 2022-03-27 17:51 UTC by Pow3r5

## Overview: What does this pull request change?

Reviewed tutorials\configurations.rst. Edited simple mistakes such as Manim not being capitalized and commas.

## Motivation and Explanation: Why and how do your changes improve the library?

My motivation was to start getting involved in the open-source community. This improves the library as it increases readability and professionalism.

## Links to added or changed documentation pages

## Further Information and Comments

Closes https://github.com/ManimCommunity/manim/issues/1401

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-03-28 14:29 UTC, tameTNT commented
Would it be possible for you to edit your comment to remove the `closes` keyword so that #1401 remains open after your PR has been approved?

2022-03-28 15:45 UTC, Pow3r5 commented
> Would it be possible for you to edit your comment to remove the `closes` keyword so that #1401 remains open after your PR has been approved?

Yep will do sorry about that

2022-04-01 10:57 UTC, tameTNT approved these changes
These changes all seem good to me. As you say, mainly just capitalising `manim` and improving clarity with commas.

2022-04-01 10:57 UTC, tameTNT commented on docs/source/tutorials/configuration.rst
> +for a list of all CLI flags and all config options.
```suggestion
for a list of all CLI flags and config options.
```
Second `all` is unnecessary I think.

2022-04-03 08:18 UTC, Darylgolden requested changes

2022-04-03 08:18 UTC, Darylgolden commented on docs/source/tutorials/configuration.rst
> +By far, the most commonly used command in the CLI is the ``render`` command,
```suggestion
By far the most commonly used command in the CLI is the ``render`` command,
```

I believe this is incorrect.

2022-04-03 08:18 UTC, Darylgolden commented on docs/source/tutorials/configuration.rst
> +which is used to render the scene(s) to an output file.
```suggestion
which is used to render scene(s) to an output file.
```

2022-04-15 21:17 UTC, behackl commented on docs/source/tutorials/configuration.rst
> +The most common, simplest, and recommended way to set the configure Manim is
```suggestion
The most common, simplest, and recommended way to configure Manim is
```

2022-04-15 21:19 UTC, behackl approved these changes
Thank you for your efforts! I've added one more suggestion myself and applied all of the suggestions; this is good to go now. :-)

2022-04-15 21:21 UTC, merged