Speed Control for animations
ManimCommunity/manim pull request #2749
Opened 2022-06-02 13:54 UTC by sparshg

## Overview: What does this pull request change?

## Motivation and Explanation: Why and how do your changes improve the library?

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-06-06 13:40 UTC, behackl reviewed
Thank you for your reworked contribution! This is indeed much cleaner than the last approach, I like it quite a lot!

I have not fully read the code yet (but am mainly just missing the static `add_updater` method, which seems a bit odd to me, but I think I understand the idea behind it), but from what I have read I think this is in a pretty good state already. Take a look at my comments for more detailed remarks. :-)

2022-06-07 17:15 UTC, sparshg commented on manim/animation/speedmodifier.py
> +            ChangeSpeed.dt = (newx - self.t) * self.anim.run_time
I didn't consider several ChangeSpeed animations playing at once. Even if many animations play, there can only be single `dt` for the scene/updaters. So, we have to explicitly define which animation is going to control `dt` in such a case.  Only one `ChangeSpeed` animation at a time can have this ability which is why I added a class variable `is_changing_dt`. I added a bool parameter `affects_speed_updaters` which if true, can control `ChangeSpeed.dt`. If multiple animations try to do so together, I can detect that using `is_changin_dt` class variable leading to assertion error

2022-06-07 18:15 UTC, sparshg commented
Thanks for the review, I guess I addressed all of your comments and fixed the bugs I could find.

2022-06-09 15:42 UTC, sparshg commented on manim/animation/speedmodifier.py
> +class ChangedWait(Wait):
Thanks, this one was really useful.

2022-06-20 15:09 UTC, kilacoda approved these changes

2022-07-04 22:03 UTC, behackl requested changes
Sorry for the long time since my last review -- I'm very happy with this PR at this point! The last few issues I see with this:

- I've left a bunch of suggestions concerning formatting of the docstrings, please take a look,
- `ChangeSpeed.add_updater` *really* should have a docstring to explain what the method is used for. I don't think that rendered examples are necessary, but it should definitely have a short description,
- and finally, new functionality should be tested: I'd recommend copy-pasting the code for `SpeedModifierExample` to a test (I can help with that in case you don't want to look into how tests work; just let me know in case.

Other than that this seems good to go; pretty cool stuff -- thanks for your efforts!

2022-07-05 13:31 UTC, behackl approved these changes
I've left one final suggestion to further improve the docstring of `ChangeSpeed.add_updater`, but other than that I have no further comments. Looks good to me, very cool!

2022-07-06 14:39 UTC, merged