Transform matching
ManimCommunity/manim pull request #2826
Opened 2022-06-17 04:17 UTC by Swiddis

## Overview: What does this pull request change?

`manim.animation.transform_matching_parts.TransformMatchingAbstractBase` is leaking transparent Mobjects into scenes (see #2763) due to a faulty cleanup process that marks the transformation target object for deletion. This PR:
- Avoids duplicating the target when building FadeIn to avoid leaks
- Fixes the cleanup process to avoid deleting the target
- Adds graphical tests to check the corrected behavior
- Resolves #2763 

## Motivation and Explanation: Why and how do your changes improve the library?

## Links to added or changed documentation pages

## Further Information and Comments

The skipping `FadeIn` interpolation fix is potentially fragile, see discussion in #2763.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-06-18 13:05 UTC, MrDiver requested changes
Instead of putting a random if else in the code i think it might be better to reuse the existing code with `self.to_remove` and change the cleanup process instead! Should yield the same result as your changes.

Tell me what you think about that!

you can add in line 125
```py
fade_target_copy = fade_target.copy()
```

change line 140
```py
self.to_remove = [mobject, fade_target_copy]
```

2022-06-18 13:05 UTC, MrDiver commented on manim/animation/transform_matching_parts.py
>          scene.remove(self.to_remove)
when doing a removal list instead of a single mobject
```suggestion
        scene.remove(*self.to_remove)
```

2022-06-18 13:05 UTC, MrDiver commented on manim/animation/transform_matching_parts.py
> +                FadeIn(fade_target, target_position=fade_target, **kwargs),
```suggestion
                FadeIn(fade_target_copy, target_position=fade_target, **kwargs),
```

2022-06-18 22:41 UTC, Swiddis commented
@MrDiver I like this solution. I originally tried something like it with a copy of the target, but it wound up introducing another bug. Yours avoids that, so I'm happy to add the changes.

Interestingly, the final target rendering looks slightly different, which failed one of the tests I added. I just re-set the data since I couldn't find anything off visually, but worth noting that there seems to be a behavioral difference between the solutions.

2022-06-18 22:44 UTC, MrDiver commented
We should probably generate the test data from the unchanged code and then test if it still does the same thing. @Swiddis

2022-06-18 22:55 UTC, Swiddis commented
@MrDiver I tried it and it looks like the existing behavior matches with the skip-fadein version, and differs from the copy version.

2022-06-18 22:57 UTC, MrDiver commented
@Swiddis is there anything that comes up when you run the test with `--show_diff`?

2022-06-18 23:19 UTC, Swiddis commented
No, wait, mine doesn't work either, it looks like I messed something up when setting the test data. Both of our versions are different from the original in the same way.

2022-06-18 23:42 UTC, MrDiver commented
@Swiddis No worries the test data system really keeps one struggling if everything has worked the way it should.

I'll just leave this open for now and if tomorrow there's no change it can be merged i suppose.

Who would have guessed that so few lines of code could create so much trouble!

Still thanks a lot for your work!

2022-06-19 08:37 UTC, MrDiver approved these changes

2022-06-19 08:39 UTC, merged