Fix formatting and grammar issues in :doc:/contributing/development
ManimCommunity/manim pull request #2904
Opened 2022-07-27 12:38 UTC by bolded

## Overview: What does this pull request change?

- Removed a reference to a non-existent (404) flowchart at the bottom of the page
- Changed list element to be more consistent
- Capitalized Manim where necessary
- Fixed grammar referring to Graphviz dependency

## Motivation and Explanation: Why and how do your changes improve the library?

## Links to added or changed documentation pages

## Further Information and Comments

If an image is available for the flowchart, it would be best to update it instead of removing the reference altogether. It seems that it may have been a 404 for a long time.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-09-29 09:47 UTC, sparshg approved these changes
Looks good, thanks!

2022-10-05 13:30 UTC, behackl requested changes
LGTM, except for one particular proposed change. In case I don't hear back, I'll change it and merge this then. Sorry for the long delay!

2022-10-05 13:30 UTC, behackl commented on docs/source/contributing/development.rst
> +   This will ensure during development that each of your commits are properly
each ... is, or alternatively something like all ... are, but I don't agree with this proposed change as is.

2022-10-08 19:30 UTC, behackl approved these changes
Resolved conflict and commited suggested change. Ready to be merged, thanks for your contribution!

2022-10-08 19:32 UTC, merged