Homotopy example
ManimCommunity/manim pull request #2959
Opened 2022-09-23 15:57 UTC by rli596

Added a simple example for Homotopy animation

## Overview: What does this pull request change?

## Motivation and Explanation: Why and how do your changes improve the library?

## Links to added or changed documentation pages

https://manimce--2959.org.readthedocs.build/en/2915/reference/manim.animation.movement.Homotopy.html

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-09-25 14:32 UTC, alembcke commented
The link you provided is for the main documentation page.  Here is the link for this specific PR, which shows your added example:
https://manimce--2959.org.readthedocs.build/en/2915/reference/manim.animation.movement.Homotopy.html

2022-09-29 08:39 UTC, sparshg requested changes

2022-09-29 08:39 UTC, sparshg commented on manim/animation/movement.py
> +                self.play(Homotopy(homotopy, dot))
Currently it look just like shifting the dot. How about something like this waving square:
```suggestion
                square = Square()
                homotopy = lambda x, y, z, t: (x, y + 0.2 * np.sin(x + 10 * t), z)
                self.play(Homotopy(homotopy, square))
```

https://user-images.githubusercontent.com/43041139/192983555-1a602921-51fd-4b66-97b9-9ede4757fcda.mp4

2022-11-15 04:48 UTC, behackl commented on manim/animation/movement.py
> +                self.play(Homotopy(homotopy, dot))
I like the suggestion of @sparshg, but dislike that the square is already deformed in the initial step. I have an alternate suggestion of a more classical example of a homotopy:

```suggestion
    .. manim:: HomotopyExample

        import math

        class HomotopyExample(Scene):
            def construct(self):
                square = Square()
                square.insert_n_curves(20)  # improve quality of homotopy target
                homotopy_map = lambda x, y, z, t: (
                    (1-t)*x + t*2*np.cos(math.atan2(y, x)),
                    (1-t)*y + t*2*np.sin(math.atan2(y, x)),
                    z,
                )
                self.play(Homotopy(homotopy_map, square))
```

2022-11-15 04:50 UTC, behackl commented on manim/animation/movement.py
> +                self.play(Homotopy(homotopy, dot))
Output:

https://user-images.githubusercontent.com/11851593/201829134-db90993c-5945-41e9-a3f6-951ab7cf530a.mp4

What do you think?

2022-11-15 10:46 UTC, rli596 commented
Having a more interesting shape to apply the homotopy to is good, but I think the homotopy itself should be kept as mathematically simple as possible. This was my original reasoning behind choosing a dot too, but it might have been too simplistic.

But I like the square to circle deformation as a mathematically classical example of homotopy.

2022-11-15 11:30 UTC, rli596 commented
There's another use case which is very different to traditional homotopy: dynamic solutions. For example, a function of the form f(x,t) can be implemented using

homotopy = lambda x,y,z,t: np.array([x, f(x,t), 0])

applied to say, a straight line y = constant. Would it be worth including an example for this use case?

2022-11-15 16:14 UTC, behackl commented
> There's another use case which is very different to traditional homotopy: dynamic solutions. For example, a function of the form f(x,t) can be implemented using
> 
> homotopy = lambda x,y,z,t: np.array([x, f(x,t), 0])
> 
> applied to say, a straight line y = constant. Would it be worth including an example for this use case?

Definitely, it would be nice to have a second small, perhaps easier to read example!

2024-09-01 02:26 UTC, JasonGrace2282 commented
Closing due to a lack of a response, feel free to reopen.

2024-09-01 02:26 UTC, closed without merging