docs: CycleTransform documentation & example
ManimCommunity/manim pull request #2978
Opened 2022-10-04 12:53 UTC by jeertmans

## Overview: What does this pull request change?

This PR adds a documentation to the `CyclicReplace` transformation, with an example.

## Motivation and Explanation: Why and how do your changes improve the library?

I think keeping the documentation up-to-date is important.

## Links to added or changed documentation pages

## Reviewer Checklist
- [x] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [x] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [x] If applicable: newly added functions and classes are tested

2022-10-06 00:08 UTC, alembcke commented
Thank you for contributing this, I agree that keeping the documentation up-to-date is important.

What are your thoughts about repeating the `CyclicReplace` four times, so that the video plays in a perfect loop?

2022-10-06 07:48 UTC, jeertmans commented
Indeed, @alembcke, that's a good idea! The animation now looks much nicer ;-)

2022-10-28 15:02 UTC, behackl requested changes
Thank you very much for your contribution! In general this is fine, I just left a few suggestions for improvement. Please let me know whether you are able to take a look and apply them / discuss them -- and otherwise we will apply them in a while and then merge this.

2022-10-28 15:02 UTC, behackl commented on manim/animation/transform.py
> +        Further keyword arguments that are passed to :class:`Transform`.
```suggestion
        Further keyword arguments that are passed to :class:`.Transform`.
```

2022-10-28 15:02 UTC, behackl commented on manim/animation/transform.py
> +                    self.play(CyclicReplace(*group))
Minor changes to improve readability.

```suggestion
        class CyclicReplaceExample(Scene):
            def construct(self):
                group = VGroup(Square(), Circle(), Triangle(), Star())
                group.arrange(RIGHT)
                self.add(group)

                for _ in range(4):
                    self.play(CyclicReplace(*group))
```

2022-10-28 20:02 UTC, jeertmans commented
Hi @behackl, Thanks for the review! I am perfectly fine with all suggested changes! It’s my first contribution to Manim, so I expected to not exactly match your common style guidelines :)

2022-10-28 21:39 UTC, behackl approved these changes
Thank you!

2022-10-28 21:39 UTC, merged