Convert all types of parameters in docstrings to proper type annotations
ManimCommunity/manim pull request #2988
Opened 2022-10-12 15:36 UTC by NotWearingPants

## Overview: What does this pull request change?
I have gone through all of the types of parameters in docstrings and:
- If there was no type annotation for that parameter I annotated with the type from the docstring (and added the necessary imports)
- If there was (so the docstring type is redundant) I checked they were the same and deleted the docstring type
- If the docstring mentioned a param which does not exist I fixed it
- Reformatted function signatures that became longer than 88 chars after my changes
- Fixed some more docstring issues I found
- There are now zero types in the "parameters" section of docstrings across the library

## Motivation and Explanation: Why and how do your changes improve the library?
Advances progress in #2121 by a lot 🎉
There are still return types and attribute types in docstrings, maybe I'll do them next.

## Links to added or changed documentation pages

## Further Information and Comments
I wrote a script to help me automate a lot of the process, and manually did what I couldn't automate.

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2022-10-15 12:33 UTC, NotWearingPants commented
The first commit was created by running [this script I wrote](https://github.com/NotWearingPants/manim-refactoring-script), so if you prefer you can review the script instead of the diff it created.

For the 2nd commit I ran `isort` and for the 3rd commit I ran `black`, but the 4th commit was done manually so it also requires reviewing.

2022-11-02 10:55 UTC, behackl requested changes
Very impressive work, kudos! I have a bunch of minor suggestions / change requests, but am overall very happy with this. This is indeed a substantial step in the direction of a fully typed library! 🥳 

Please let me know if you can take a look at my comments, otherwise I'll work on resolving them in order to get this PR merged ASAP. Thanks!

2022-11-02 10:55 UTC, behackl commented on manim/camera/camera.py
>          """Initialises the Camera.
The docstring of `Camera.__init__` should actually live in the class docstring of `Camera` (otherwise it won't show up in the built documentation).

2022-11-02 10:55 UTC, behackl commented on manim/camera/camera.py
> +            If not set, the background is filled with `self.background_color`
```suggestion
            If not set, the background is filled with :attr:`background_color`
```

or

```suggestion
            If not set, the background is filled with ``self.background_color``
```

(I'd prefer the first.)

2022-11-02 10:55 UTC, behackl commented on manim/mobject/types/image_mobject.py
> +            * 'bicubic' or 'cubic'
See https://manimce--2988.org.readthedocs.build/en/2988/reference/manim.mobject.types.image_mobject.AbstractImageMobject.html#manim.mobject.types.image_mobject.AbstractImageMobject.set_resampling_algorithm -- if this should be formatted as a list, there has to be a newline between lines 69 and 70.

2022-11-02 10:55 UTC, behackl commented on manim/scene/scene.py
> +            named parameters affecting what was passed in ``animations``,
```suggestion
            Named parameters affecting what was passed in ``animations``,
```

2022-11-06 21:24 UTC, behackl requested changes
I could not push my changes here directly, so I have made a PR to your fork: https://github.com/NotWearingPants/manim/pull/1 -- please take a look, I'd like to get this merged rather sooner than later. :-)

2022-11-10 06:16 UTC, behackl approved these changes
I am merging this PR as-is, and will add the remaining changes via a follow-up PR.

Thanks again for your contribution!

2022-11-10 06:17 UTC, merged

2022-11-14 07:11 UTC, NotWearingPants commented
@behackl I'm sorry I wasn't responsive this month so far, I've been busy with school work unfortunately (semester started recently).
Thank you for your efforts to merge the PRs!!
Hopefully I'll find time to work on more stuff here, like converting attribute types from docstrings.