feat: DecimalNumber() - added spacing between values and unit
ManimCommunity/manim pull request #3366
Opened 2023-09-10 11:58 UTC by uwezi

## Overview: What does this pull request change?

- added the parameter `unit_buff_per_font_unit` to add additional space between the numeric values and the unit
- default value `unit_buff_per_font_unit=0` ensures backward compatibility
- also added parameter documentation in docstring

## Motivation and Explanation: Why and how do your changes improve the library?
According to general rules of typesetting a spacing between a numeric value and a unit is required. In Manim this is currently not possible, since leading non-printing characters in the `unit` would be stripped automatically.

![image](https://github.com/ManimCommunity/manim/assets/8582807/753a2e55-235e-4637-88c4-1fd4e036e87c)
```python
class decTest(Scene):
    def construct(self):
        num1 = DecimalNumber(34.67, unit=r"\text{km}")
        self.add(num1)
        num2 = DecimalNumber(34.67, unit=r"\text{km}", unit_buff_per_font_unit=0.003)
        self.add(num2.next_to(num1,DOWN))
```

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2023-10-15 04:24 UTC, TheMathematicFanatic approved these changes
Good idea and makes sense! I worry about the alignment if a unit has a character with a low tail in it like mg, won't it be too high? I don't know of a good general solution to this problem. This is my first review 😁 Just kidding I guess this is my first comment...

2023-10-15 04:26 UTC, TheMathematicFanatic approved these changes

2023-10-15 09:40 UTC, uwezi commented
> Good idea and makes sense! I worry about the alignment if a unit has a character with a low tail in it like mg, won't it be too high? I don't know of a good general solution to this problem. 

Since I only added horizontal space to the existing object, the vertical alignment should not be affected from how it already is today.
But yes, you might be right - already today the vertical alignment will probably be off, because the numbers and units are not aligned to their baseline, since Manim's Tex-rendering currently does not recognize the baseline...

2023-10-22 20:30 UTC, behackl requested changes
Seems like a fine addition to me, thanks for your contribution! I've left a bunch of suggestions for improving the formatting of the docstring, please take a look. Thanks!

2023-10-22 20:30 UTC, behackl commented on manim/mobject/text/numbers.py
> +        The numeric value to be displayed. It can later be modified using `.set_value()`.
```suggestion
        The numeric value to be displayed. It can later be modified using :meth:`.set_value`.
```

2023-10-22 20:30 UTC, behackl commented on manim/mobject/text/numbers.py
> +        The class for rendering digits and units, by default `MathTex`.
```suggestion
        The class for rendering digits and units, by default :class:`.MathTex`.
```

2023-10-22 20:30 UTC, behackl commented on manim/mobject/text/numbers.py
> +        Set to `True` to include a sign for positive numbers and zero.
```suggestion
        Set to ``True`` to include a sign for positive numbers and zero.
```

2023-10-22 20:30 UTC, behackl commented on manim/mobject/text/numbers.py
> +        When `True` thousands groups are separated by commas for readability.
```suggestion
        When ``True`` thousands groups are separated by commas for readability.
```

2023-10-22 20:30 UTC, behackl commented on manim/mobject/text/numbers.py
> +        When a number has been truncated by rounding, indicate with an ellipsis (...).
```suggestion
        When a number has been truncated by rounding, indicate with an ellipsis (``...``).
```

2023-10-22 20:30 UTC, behackl commented on manim/mobject/text/numbers.py
> +        of `unit_buff_per_font_unit=0.003` gives a decent spacing. Scales with font size.
```suggestion
        of ``unit_buff_per_font_unit=0.003`` gives a decent spacing. Scales with font size.
```

2023-10-22 20:30 UTC, behackl commented on manim/mobject/text/numbers.py
> +        Size of the font
```suggestion
        Size of the font.
```

2023-11-04 14:06 UTC, behackl approved these changes
LGTM now, thanks!

2023-11-04 14:07 UTC, merged