Adding documentation
ManimCommunity/manim pull request #3408
Opened 2023-10-15 22:42 UTC by TheMathematicFanatic

## Overview: What does this pull request change?

Added documentation and example renders for mobject's .to_edge and .to_corner methods

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2023-10-16 10:33 UTC, Uiblar approved these changes
Simple and clear/understandable. Thanks!

2023-10-16 10:36 UTC, Uiblar approved these changes

2023-10-22 19:00 UTC, behackl requested changes
Thanks for your contribution! Two minor issues with your current proposal:

- the added docstrings are missing the `Parameters`-section which explain the input arguments,
- the two examples you chose are nice in principle -- however, they don't strictly need to be animated. (We are currently running into an issue with our documentation build time, and every added rendered animation tends to add a few more seconds to it -- static images are more or less fine though.) Could you think of a way where these two methods are illustrated with static images instead?

2023-12-10 14:28 UTC, MrDiver reviewed
Changes for the animations to be static

2023-12-10 14:28 UTC, MrDiver commented on manim/mobject/mobject.py
> +                    self.wait()
```suggestion
        .. manim:: ToCornerExample

            class ToCornerExample(Scene):
                def construct(self):
                    c = Circle()
                    c.to_corner(UR)
                    t = Tex("To the corner!")
                    t2 = MathTex("x^3").shift(DOWN)
                    self.add(c,t,t2)
                    t.to_corner(DL, buff=0)
                    t2.to_corner(UL, buff=1.5)
```

2023-12-10 14:28 UTC, MrDiver commented on manim/mobject/mobject.py
> +                    self.wait()
```suggestion
            class ToEdgeExample(Scene):
                def construct(self):
                    tex_top = Tex("I am at the top!")
                    tex_top.to_edge(UP)
                    tex_side = Tex("I am moving to the side!")
                    c = Circle().shift(2*DOWN)
                    self.add(tex_top, tex_side)
                    tex_side.to_edge(LEFT)
                    c.to_edge(RIGHT, buff=0)
                    
```

2023-12-10 15:04 UTC, MrDiver commented on manim/mobject/mobject.py
> +            class ToCornerExample(Scene):
```suggestion
        .. manim:: ToCornerExample
            :save_last_frame:

            class ToCornerExample(Scene):
```

2023-12-10 15:04 UTC, MrDiver commented on manim/mobject/mobject.py
> +            class ToEdgeExample(Scene):
```suggestion
        .. manim:: ToEdgeExample
            :save_last_frame:
            class ToEdgeExample(Scene):
```

2023-12-10 15:46 UTC, MrDiver commented on manim/mobject/mobject.py
> +            class ToEdgeExample(Scene):
```suggestion
            :save_last_frame:
            
            class ToEdgeExample(Scene):
```

2023-12-13 03:22 UTC, JasonGrace2282 approved these changes
LGTM

2023-12-13 11:06 UTC, merged