Allow 3DArrows to utilize GrowArrow()
ManimCommunity/manim pull request #3488
Opened 2023-12-03 04:48 UTC by RishabhSaini

## Overview: What does this pull request change?
Adds a `scale` function to the Arrow3D Class in three_dimensions to prevent it from falling back to the default implemented in `mobject` which lacks implementation for handling the scaling of the conical tip of the arrow. Similar to the 2D version, it handles scaling the arrow.

## Motivation and Explanation: Why and how do your changes improve the library?
Resolves: #3481 
Allows `self.play(GrowArrow(Arrow3D(LEFT, RIGHT)))` 

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2023-12-04 02:46 UTC, chopan050 requested changes
Hello, Rishabh! Thanks for your contribution.

While this implementation _does indeed prevent a crash_... it turns out **it will create other crashes related to using `Arrow3D.scale`.** 

You see... you copied and pasted almost all the code `Arrow.scale()` in here (except for a removed call to `self._set_stroke_width_from_length()`, but I'll talk about that one later). The thing is, one shouldn't just do that without checking whether the code really fits this new place, and must adapt it if necessary.

In this case, there **are** some things that must be adapted.
(1) is a minor nitpick.
(2) is actually a **huge problem that must be fixed: the crashes I mentioned**.

1. If you look at the docstrings for the original `Arrow.scale()` method you copied, the first line says:
```py
def scale(self, factor: float, scale_tips: bool = False, **kwargs) -> Self:
    r"""Scale an arrow, but keep stroke width and arrow tip size fixed. (...)"""
```
_Stroke width_ and _arrow tip size_ **do not change** during the scaling of `Arrow`. However, by playing your animation for `Arrow3D` with a longer runtime:
```py
self.play(GrowArrow(my_arrow), run_time=5)
```
one can see that this is not the case: both the cylinder width and the cone size are also growing/scaling. One could say it's not very important, the animation works after all. But then it becomes no different from doing just:
```py
self.play(GrowFromPoint(my_arrow, my_arrow.get_start()))
```
which is equivalent to the (admittedly convoluted) following:
```py
initial_mob = arrow.copy().scale(0, about_point=arrow.get_start())
self.play(Transform(initial_mob, arrow))
```

`GrowFromPoint`, as its name says, grows a Mobject from some starting point, i.e. it scales it from 0% to 100%. That's its intention: to grow a Mobject **entirely**.

However, `GrowArrow` is a subclass of `GrowFromPoint` which was _specifically designed_ for `Arrow`s, because they scale in a different way.

Therefore, to be more consistent with `Arrow` and have an animation which is different enough from just `GrowFromPoint`, `Transform`, or even `.animate.scale()`, it would be good to fix the width of the cylinder and the size of the cone.

Which leads me to:

2. The reason you removed that `self._set_stroke_width_from_length()` call, is because **it crashed**.

It crashed, because `Arrow3D` **does not have that method**. Only `Arrow`, and thus its subclasses `Vector` and `DoubleArrow`, have it.

Other methods in the code that `Arrow3D` **does not have** are `has_tip()`, `has_start_tip()`, `pop_tips()` and `add_tip()`. Those are methods for a `TipableVMobject`, among whose subclasses are `Arc`, `Line` and `Arrow`... but not `Arrow3D`, as this is instead a subclass of `Line3D`, subclass of `Cylinder`, subclass of `Surface`, which is not related to `TipableVMobject`.

**This is actually a huge problem!** If I run:
```py
self.play(my_arrow.animate.scale(2))
```
it **crashes**, because it will run the line
```py
has_tip = self.has_tip()
```
will discover that `Arrow3D` does not have `has_tip()`, and will fail.

So, some lessons:
- **Take care that the code you put in there is safe from crashes. Take care that it doesn't reference non-existent methods or attributes.**
- If you are moving a code from a class to another, make sure to adapt it to comply with the above.

Now... if you plan to change `Arrow3D.scale()` so that it complies with everything I mentioned, be aware that:
- if you're going to mantain the size of the tip, the attribute is not called `Arrow3D.tip`. It's actually called `Arrow3D.cone`, because it's a `Cone` VMobject.
- the original `Arrow`, in order to mantain the stroke width of its line, used its `Arrow._set_stroke_width_from_length()` that must have caused your original crash. For `Arrow3D` you would have to create a similar method which preserves (under certain conditions, of course) the width of the `Line3D`, which is a subclass of `Cylinder`, when you're scaling it, so that it only stretches or squeezes along its main direction.

Those are my comments. I hope that this does not discourage you from contributing: it can, indeed, be daunting sometimes, but I think that you can get on the right track soon.

Cheers!

2023-12-08 22:00 UTC, chopan050 commented
I tried rendering the following scene, but the tip doesn't move properly:
```py
class Simple(ThreeDScene):
    def construct(self):
        arrow = Arrow3D(resolution=(1, 12))
        self.add(arrow)
        self.wait()
        self.play(arrow.animate.scale(3), run_time=5)
        self.wait()
        arrow.scale(1/3)
        self.wait()
        arrow.scale(2)
        self.wait()
        arrow.scale(1/2)
        self.wait()
```

https://github.com/ManimCommunity/manim/assets/49853152/95f28c6d-3d7e-4efd-8d85-c420806f0f5a

- The length of the arrow scales fine.
- I don't think that the actual width of the arrow line should change, for the reasons mentioned before (unless some specific conditions apply, the same conditions as for `Arrow`).
- The tip of the arrow is not scaling, which by itself is sort of fine, but it's not moving correctly. Also, the width of the line should be consistent with this behavior of not scaling.

2023-12-09 16:20 UTC, RishabhSaini commented
> * I don't think that the actual width of the arrow line should change, for the reasons mentioned before (unless some specific conditions apply, the same conditions as for `Arrow`).

Scaling a 2D arrow without scaling_tips also results in a behavior where the width of the arrow increases and the tips also increase

https://github.com/ManimCommunity/manim/assets/10206278/498e1003-fd43-47b1-a925-4ecd4b7eab49

2023-12-09 18:56 UTC, RishabhSaini commented
Hence it looks like this issue stems from the 2D arrow not scaling properly when the `scale_tips` is set to true. Hence this issue blocks on the correct implementation for the `add_tip` (rotation fails when the tips are not scaled) on the 2D arrow.

2023-12-15 20:44 UTC, chopan050 commented
Hello, sorry for not commenting for that long.

It's true that the tip and width _do_ scale with `GrowArrow` or `scale_tips=True`, as you show in the animation.

However, I was talking about the case where you use `scale()` with the default parameters. Try running
```py
class Test(Scene):
    def construct(self):
        self.play(Arrow().animate.scale(3), run_time=3
```
and see what happens, and compare with the previous video I sent with `Arrow3D`.
https://github.com/ManimCommunity/manim/assets/49853152/062cd9e7-4513-4da2-8dda-e7d39734f628

2024-07-13 18:51 UTC, closed without merging

2024-07-13 18:51 UTC, JasonGrace2282 commented
Closed due to inactivity