Deferred Animation builder to only modify mobjects after the animation is actually played
ManimCommunity/manim pull request #3502
Opened 2023-12-07 13:58 UTC by MrDiver

Passing a flag to `.animate` was a bit too complicated and would destroy the property aspect of it, now we can also use `deferred` as a property.

I split the `_AnimationBuilder` into two subclasses which fulfill their respective roles, whereas `_ImmediateAnimationBuilder` is the usual builder that we know and love and `_DeferredAnimationBuilder` is the new builder which actually is delaying the building of the state until the animation is played. I added an example to the documentation, I am not sure if I should add tests for that or what would be a useful test.

But first i would like to discuss the concept, i linked a documentation page for this.

https://manimce--3502.org.readthedocs.build/en/3502/reference/manim.mobject.mobject.Mobject.html?highlight=deferred#deferredexample

```py
class MinimalExample(Scene):
    def construct(self):
        objects = []
        animations = []
        animations2 = []

        for i in range(10):
            m = Square().set_color(BLUE).set_fill(opacity=0.3).scale(0.5)
            objects.append(m)
            animations.append(ReplacementTransform(m.copy(),m))
            if i % 2 == 0:
                animations2.append(m.animate.set_color(GREEN))
            else:
                animations2.append(FadeOut(m))

        group = VGroup(*objects).arrange_in_grid()
        self.play(*animations, run_time=2)
        self.wait()
        self.play(*animations2, run_time=2)
        self.wait()
        
```

vs.

```py
class Expected(Scene):
    def construct(self):
        objects = []
        animations = []
        animations2 = []
        l1 = []
        l2 = []

        for i in range(10):
            m = Square().set_color(BLUE).set_fill(opacity=0.3).scale(0.5)
            objects.append(m)
            animations.append(ReplacementTransform(m.copy(),m))
            if i % 2 == 0:
                l1.append(m)
            else:
                l2.append(m)

        group = VGroup(*objects).arrange_in_grid()
        self.play(*animations, run_time=2)
        self.wait()
        self.play(*[x.animate.set_color(GREEN) for x in l1],*[FadeOut(x) for x in l2], run_time=2)
        self.wait()```

2023-12-08 22:03 UTC, chopan050 commented
Marked as draft, as requested by MrDiver internally.

2023-12-12 12:36 UTC, behackl commented
Are there usecases for both the deferred and the immediate builder? I can see how the deferred one is useful. 🤔

2023-12-12 17:48 UTC, MrDiver commented
> Are there usecases for both the deferred and the immediate builder? I can see how the deferred one is useful. 🤔

It definitely broke a lot of tests when i only used the deferred one, so maybe there are a lot of edge cases where it's useful to have `.animate` i am not sure how changing the default to deferred would affect everything but i must say i also haven't looked to deep into why the tests are failing and assumed it was my sloppy implementation at that point.

2024-04-01 03:29 UTC, MrDiver commented
I think the main benefit might lie in combination with `AnimationGroup`.
Such that you can build a list of animations with the deferred animation builder and then later on use them in an animation group for complex transitions which depend on the current state of the scene and not when the Mobjects were created.

2026-06-11 19:41 UTC, chopan050 requested changes
I took a look at this PR and the changes look nice!

There's one thing we have to deal with: the fact that the `_DeferredAnimationBuilder.methods` list temporarily contains tuples of 4 elements rather than 3, where the 4th one is a `has_overridden_animation` boolean, conflicts with the changes I made in PR #4315 where I replace the 3-tuples `(method, args, kwargs)` with instances of a new dataclass `MethodWithArgs`. Thus, in order to merge this PR, we need to figure out how to deal with this situation. I can think of two approaches right now:
- saving all these booleans into a new list as a different attribute of `_DeferredAnimationBuilder`
- temporarily saving them inside `MethodWithArgs.kwargs`

2026-08-20 20:48 UTC, closed without merging