Doc: add docstrings to Brace
ManimCommunity/manim pull request #3715
Opened 2024-04-22 09:05 UTC by biinnnggggg

## Overview: What does this pull request change?

Add docstrings to methods in Brace so that sphinx will create hyperlinks to these methods.

## Links to added or changed documentation pages

## Further Information and Comments

Related to #3597

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2024-04-22 11:28 UTC, JasonGrace2282 commented
Is it possible to add some doc tests as well?
You can see an example [here](https://github.com/ManimCommunity/manim/blob/main/manim%2Fmobject%2Fmobject.py#L404-L408).
Thanks for improving the documentation :)

2024-04-24 17:59 UTC, behackl requested changes
Looks fine, thanks! I've left one minor comment about the added type hint, please take a look.

2024-04-24 17:59 UTC, behackl commented on manim/mobject/svg/brace.py
> +        mob : :class:`~.Mobject`
Type hints should be added to the parameters themselves, not to the docstring.

```suggestion
        mob
```

2024-05-28 01:03 UTC, JasonGrace2282 approved these changes
Thanks for your work here!

2024-06-30 10:22 UTC, behackl approved these changes
Sorry for the long wait, thanks for your efforts!

2024-06-30 10:35 UTC, merged