Add shorthand for axes
ManimCommunity/manim pull request #3754
Opened 2024-05-09 11:42 UTC by JasonGrace2282

Allows `ax @ (1, 0, 0)` for `coords_to_point` and `(1, 0, 0) @ ax` for `point_to_coords`

2024-05-09 13:09 UTC, behackl approved these changes
I like this a lot! 👍 

It might make sense modify or include a new example in the example gallery that uses this notation.

2024-05-09 16:30 UTC, Viicos requested changes

2024-05-09 19:32 UTC, JasonGrace2282 commented on manim/mobject/graphing/coordinate_systems.py
> +        return self.coords_to_point(*coord)
The problem with removing the `*` is that `ax @ (1, 0, 0)` then returns a 3x3 array, which I felt was kinda unintuitive.

2024-05-12 01:32 UTC, JasonGrace2282 commented
I just added it to `NumberLine` and changed the `CoordinateSystem` example to use `@` notation. In the future, maybe we should transition to that being the "standard" (although `c2p` can always exist for more complex expressions)

2024-05-23 15:14 UTC, Viicos commented
Will get back to the unresolved comment soon

2024-05-27 12:15 UTC, Viicos approved these changes

2024-05-27 12:15 UTC, Viicos commented on manim/mobject/graphing/coordinate_systems.py
> +    def coords_to_point(self, *coords: Point3D):
```suggestion
    def coords_to_point(self, *coords: ManimFloat):
```

This is what got me confused regarding my other comment

2024-05-27 17:34 UTC, merged