Fixes #3749 Digraph FadeOut
ManimCommunity/manim pull request #3786
Opened 2024-05-29 04:28 UTC by Nikhil-42

## Overview: What does this pull request change?
This pull request resolves issue #3749 in which edges do not FadeOut properly when using DiGraph. The default updater in the DiGraph class used the edge constructor `.become` to attach the edges to the vertices. I replaced the updater to function more similarly to the Graph updater which moves the endpoints of the Line. Also, noticed that `Line::set_points_by_ends` did not project onto the bounding box of `start` and `end` so I updated the behavior to match the constructor and the type hints to align with usage in the example scenes.

Documented behavior of `Line::set_points_by_ends`
Updated type hints in `Line`
Altered edge updaters in `graph.py` to use `Line::set_points_by_ends` instead of `.become`

## Links to added or changed documentation pages

## Further Information and Comments

Fixes #3749 

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2024-06-21 15:55 UTC, chopan050 requested changes
Thanks for your contribution! Looks good in general, just one small comment.

2024-06-21 15:55 UTC, chopan050 commented on manim/mobject/geometry/line.py
> +            The angle of a circle spanned by this arc, by default 0 which is a straight line.
When adding docstrings to a method, it is not necessary to repeat the parameter type hints inside the docstring: only add typings directly to the signature.

```suggestion
        start
            The start point or Mobject of the line.
        end
            The end point or Mobject of the line.
        buff
            The empty space between start and end and the line, by default 0
        path_arc
            The angle of a circle spanned by this arc, by default 0 which is a straight line.
```

2024-06-22 01:15 UTC, Nikhil-42 commented
@chopan050 Thanks for the edit!

Side note: I'm interested in helping with the rewrite, do you know how I could get into that?

2024-06-22 20:13 UTC, chopan050 approved these changes
LGTM!

2024-06-22 20:15 UTC, chopan050 commented
> Side note: I'm interested in helping with the rewrite, do you know how I could get into that?

Any help is greatly appreciated! Simply join #dev-chat on the Manim Discord server, or the [manim/experimental] post on #development, and say that you're interested in helping. Somewhere in that post there's a list of the current tasks we have to do in experimental.

2024-06-22 20:35 UTC, merged

2024-06-23 16:29 UTC, JasonGrace2282 commented
Feel free to ping me on Discord (I'm still @JasonGrace2282 ) if you want me to walk you through where we are right now in the rewrite :)
I'm always glad to have more people interested