Rewrite contributing guide and add two troubleshooting soulutions
ManimCommunity/manim pull request #384
Opened 2020-08-31 01:21 UTC by CorvidCanine

Moved bug reporting guidelines to its own page, updated the code contribution guide to include the many notes at the end as actual steps. Adding tests and documentation probably shouldn't be in a note at the end.

This could have been in its own PR but I'm including it here; Added two solutions to issues that may arise when installing that I came across when trying to get manim to run in Raspbian.

## Changes
- Move bug reporting guidelines from contributing.md to reporting_bugs.rst
- Add reporting_bugs.rst to the index toxtree
- Add links to the repo issue page and discord server in reporting_bugs.rst
- Rewrite of the guide in contributing.md
- Add direction of developers from installation.rst to contributing.md.
- Add potential solution to missing letter from TexMobjects due to unbuilt TeX fonts in troubleshooting.rst
- Add potential solution to "LaTeX' in the OpeningManimExample displaying incorrectly due to missing python to cairo binds.

## Motivation
The code contributing guidelines were unclear and did not include important steps as actual steps.
Finding the guide to report bugs should be very easy to access.

## Testing Status
`make doctest` only reports errors for python objects not included in the toctree, which I'm not going to add in this PR.

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))
- [x] And I just rewrote them... so yes to both versions?

2020-08-31 06:47 UTC, naveen521kk requested changes
Some comments,

2020-08-31 06:47 UTC, naveen521kk commented on CONTRIBUTING.md
> +   git checkout -b <branch-name> upstream/<branch-name>
The original one was correct. People should be making an PR to master and not to any other branch,

2020-08-31 06:47 UTC, naveen521kk commented on CONTRIBUTING.md
> +   ```
Don't ask users to create virtual environments. #165 deals with it. :)

2020-08-31 06:47 UTC, naveen521kk commented on CONTRIBUTING.md
> +   which are explained in the [Installation](installation) instructions .
You should edit the installation instruction link.

2020-08-31 06:47 UTC, naveen521kk commented on docs/source/installation/troubleshooting.rst
> +  sudo apt install python3-gi-cairo
I don't think this is an issue. Because the users don't require to install pygobject to run manim and I think this won't cause a problem.

2020-09-01 08:46 UTC, huguesdevimeux commented
Converting this to draft

2020-09-02 01:30 UTC, leotrs commented
BTW, the contributing guidelines have moved to docs/source/contributing.md. Please merge from master and update this PR :)

2020-09-02 18:05 UTC, CorvidCanine commented
Thank you for looking through everything @naveen521kk. I've made the changes you suggested, except for the installation link from contributing.md. I'm not sure what's wrong with it? 
The python-cario bindings fixed the issue for me on Raspbian, but I've removed it until I/someone can do more research into this.
@leotrs Thank's for pointing out the file move.

2020-09-02 18:41 UTC, leotrs commented
Hmm for some reason your PR is now listing 302 files changed :sweat_smile: It might be easier to branch again from a fresh master and rebase your commits, if that's at all possible on your end :)

2020-09-02 22:26 UTC, CorvidCanine commented
After a not-so-elegant attempt at a rebase, github should now be showing 5 file changes by 1 new commit.

2020-09-03 02:14 UTC, leotrs approved these changes

2020-09-03 02:15 UTC, leotrs commented
LGTM! Please fix @naveen521kk 's suggestion.

@naveen521kk, if you think this is ready, let me know and I'll merge!

2020-09-03 04:14 UTC, naveen521kk requested changes
Some small suggestion

2020-09-03 04:14 UTC, naveen521kk commented on docs/source/contributing.md
> +   you can change to it with:
Let the contributing guidelines tell users to work from master.

2020-09-03 04:14 UTC, naveen521kk commented on docs/source/contributing.md
> +   pip install -r requirements.txt
This line is not required.
```suggestion
```

2020-09-03 04:14 UTC, naveen521kk commented on docs/source/installation.rst
> +Please see :doc:`contributing` for more details.
```suggestion
Please see :doc:`contributing` for more details about contributing to Manim.
```

2020-09-05 04:23 UTC, naveen521kk approved these changes
Looks good for me. Just a reminder to myself that I need to edit these in #165

2020-09-05 15:17 UTC, leotrs approved these changes

2020-09-05 15:17 UTC, merged

2020-09-05 15:17 UTC, leotrs commented
Thank you @CorvidCanine ! We look forward to your future contributions :)