feat: set_default for Animation class
ManimCommunity/manim pull request #3876
Opened 2024-07-20 16:18 UTC by christopher-hampson

## Overview: What does this pull request change?

Adds set_default class method to Animation class based on existing implementation for Mobject class.

## Motivation and Explanation: Why and how do your changes improve the library?

Addresses issue [#3142](https://github.com/ManimCommunity/manim/issues/3142)

## Links to added or changed documentation pages

## Further Information and Comments

## Reviewer Checklist
- [ ] The PR title is descriptive enough for the changelog, and the PR is labeled correctly
- [ ] If applicable: newly added non-private functions and classes have a docstring including a short summary and a PARAMETERS section
- [ ] If applicable: newly added functions and classes are tested

2024-07-20 16:27 UTC, JasonGrace2282 commented
Hello, thanks for sending a PR for this feature :)
Off of a quick look, the implementation seems fine (I'll take a closer look, hopefully later today). Would you mind adding some tests for this behavior?
Thanks for helping make Manim better :sparkle:

P.S. Don't worry about the pre-commit failure. We'll fix that in a different PR.

2024-07-21 00:15 UTC, JasonGrace2282 requested changes
Just tested and it works for me! A simple test to add would be something like
```py
def test_animation_set_default():
    s = Square()
    Rotate.set_default(run_time=100)
    anim = Rotate(s)
    assert anim.run_time == 100
```
Other than that, looks good to me :)

2024-07-21 00:15 UTC, JasonGrace2282 commented on manim/animation/animation.py
> +                    Indicate.set_default()
Thanks for writing an example (especially one that renders fast)!

2024-07-22 08:32 UTC, christopher-hampson commented
> Just tested and it works for me! A simple test to add would be something like
> 
> ```python
> def test_animation_set_default():
>     s = Square()
>     Rotate.set_default(run_time=100)
>     anim = Rotate(s)
>     assert anim.run_time == 100
> ```
> 
> Other than that, looks good to me :)

Thanks for reviewing and suggesting this test! I'll get this added shortly. :+1:

2024-07-22 09:06 UTC, behackl commented on manim/animation/animation.py
> +                    Rotate.set_default(run_time=2,rate_func=rate_functions.linear)
```suggestion
                    Rotate.set_default(run_time=2, rate_func=rate_functions.linear)
```

2024-07-22 09:06 UTC, behackl commented on manim/animation/animation.py
> +                    S = Square(color=BLUE,fill_color=BLUE,fill_opacity=0.25)
```suggestion
                    S = Square(color=BLUE, fill_color=BLUE, fill_opacity=0.25)
```

2024-07-22 09:07 UTC, behackl commented on manim/animation/animation.py
> +                    self.play(Rotate(S,PI))
```suggestion
                    self.play(Rotate(S, PI))
```

2024-07-22 11:31 UTC, JasonGrace2282 approved these changes
LGTM, thanks :)

2024-07-22 11:37 UTC, merged