Fix width (at 14 2/9 units) by default
ManimCommunity/manim pull request #415
Opened 2020-09-05 02:47 UTC by PhilipEnchin

## List of Changes
- Changed the default fixed-height to fixed-width

## Motivation
- It appears that the change from 3b1b's fixed-width by default to a fixed-height may have been incidental. To clarify, at a 16:9 aspect ratio, the frame is 14 2/9 by 8. If a square video is made, for example, 3b1b will produce a frame that's 14 2/9 by 14 2/9, whereas Manim Community will produce a frame that's 8 by 8.

## Further Comments
- I have the point illustrated in [issue 275](https://github.com/ManimCommunity/manim/issues/275#issuecomment-687534061)
- I didn't find anything indicating that this was done intentionally, hence this pull request, but perhaps someone else can confirm/deny this inference?

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

2020-09-05 08:27 UTC, behackl requested changes
Thank you for your contribution!

Technically, your changes look good to me and I agree that keeping the width fixed seems a tad more natural. Practically, the code formatting is off (you probably overstep the default line length, which is why `black` from the pipeline would like you to do this:

```diff
@@ -110,11 +110,13 @@
     background_color = colour.Color(default["background_color"])
     config["background_color"] = background_color
 
     # Set the rest of the frame properties
     config["frame_width"] = 8 * 16 / 9
-    config["frame_height"] = config["frame_width"] * config["pixel_height"] / config["pixel_width"]
+    config["frame_height"] = (
+        config["frame_width"] * config["pixel_height"] / config["pixel_width"]
+    )
     config["frame_y_radius"] = config["frame_height"] / 2
     config["frame_x_radius"] = config["frame_width"] / 2
     config["top"] = config["frame_y_radius"] * constants.UP
     config["bottom"] = config["frame_y_radius"] * constants.DOWN
     config["left_side"] = config["frame_x_radius"] * constants.LEFT
```

It would probably be also good to have this stated in the documentation somewhere; although I am not sure where. Maybe in the part about configuration -- but don't worry about that for now, maybe someone else also has a better suggestion for that.

2020-09-05 14:21 UTC, PhilipEnchin commented
Thanks for flagging the formatting issue, @behackl. I was accustomed to ignoring those, but I see now the issue with Black's formatting complaints is fixed.

I considered documenting the change in the [changelog](docs/source/changelog.rst), but I figured since this reverts the feature back to its original behaviour, it wasn't warranted. Thoughts?

2020-09-05 14:37 UTC, leotrs commented
Thanks for your contribution! I haven't looked at the code yet, I'll log on later, but let me ask a question real quick: does this change the default frame size? Or does it just fix the width instead of the height?

2020-09-05 14:54 UTC, PhilipEnchin commented
> does this change the default frame size? Or does it just fix the width instead of the height?

It doesn't affect the resolution of the video, just alters the coordinate system. Without specifying a non-16:9 apsect ratio, there's no difference. But with a different aspect ratio, the width is fixed at 14 2/9 (instead of the height being fixed at 8), which matches 3b1b's default behaviour.

I rendered a couple square videos to illustrate the point [here](https://github.com/ManimCommunity/manim/issues/275#issuecomment-687534061). (The one labeled Manim Community was rendered _before_ the change in this PR.)

2020-09-05 15:39 UTC, leotrs commented
I don't feel too strongly about this, but to me it is more natural to have the height fixed. Why? Because resolutions are usually specified as 480p, 720p, 1080p, which refer to the height, not the width. These are used regardless of the aspect ratio, so 480p and 4:3 aspect ratio gives a width of 640p etc.

Like I said, I don't know who/when this change was made but we should just pick one and stick with it instead of changing back and forth.

2020-09-05 17:47 UTC, PhilipEnchin commented
Fair enough. My experience with tools that use a fixed width (specifically Quartz Composer, then Vuo) has obviously contributed to my preference for this behaviour, but I remember finding it really intuitive all those years ago.

My motivation with this PR was to bring this feature back in line with the 3b1b's original behaviour, and with the behaviour that I've come to assume is standard. As I mentioned, I couldn't find anything to indicate that this was an intentional change, so it feels like the right move.

2020-09-07 14:20 UTC, leotrs commented
@PhilipEnchin yeah, I'm all for following a standard... it's just that at this point it's unclear whether there is a standard at all ;) 

Also, the topic of being in line with 3b1b is a delicate one. The point of this fork is to respond to the community's needs, and that necessarily means that we will depart from 3b1b in some aspects. However, I'm not sure this is one aspect that we want to depart from.... :thinking: :thinking: I'm undecided about this issue. We need the opinion of more members of the community here.

2020-09-10 20:22 UTC, PhilipEnchin commented
@leotrs Thanks! (As of today, you'll find me on discord. See you there.)

2020-10-25 19:16 UTC, leotrs commented
Unfortunately, I think this is not a priority right now and there is no consensus on whether the width or the height should be fixed. I vote we close this for now.

2020-10-25 20:29 UTC, behackl commented
> Unfortunately, I think this is not a priority right now and there is no consensus on whether the width or the height should be fixed. I vote we close this for now.

+1. Over the past few weeks, I've also gradually changed my mind when it comes to what seems more natural to me; I'm now more comfortable with having a fixed height.

2020-10-28 19:29 UTC, closed without merging

2020-10-28 19:29 UTC, leotrs commented
@PhilipEnchin Sorry this didn't work out. We very much look forward to your future contributions :)