fix #460 by enabling skipping wait statements.
ManimCommunity/manim pull request #468
Opened 2020-09-22 19:45 UTC by huguesdevimeux

## List of Changes
- Now wait can be skipped. It was not the case before; only play statement were skipped when, for example, `-n` flag was passed.  

## Explanation for Changes
What I added is pretty much a copy paste of how the skipping is handled in for self.play. It's copied from `scene.handle_caching_play`

## Testing Status
WIP  (reason why it's WIP)

## Acknowledgement
- [x] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

2020-09-23 12:07 UTC, cobordism commented
I can confirm that the issue is solved for me.

2020-09-23 12:32 UTC, behackl approved these changes
LGTM, I have also tested that it resolves #460.

2020-09-23 12:59 UTC, huguesdevimeux commented
Very nice. I will add a test and let's merge this

2020-09-23 17:02 UTC, huguesdevimeux commented
**UPDATE :** added tests. Review at will :D

2020-09-24 10:21 UTC, behackl approved these changes
Tests pass and LGTM.

2020-09-24 10:27 UTC, behackl requested changes
Sorry, I was a bit too fast: please consider the suggestion regarding the wildcard import and run black.

2020-09-24 10:27 UTC, behackl commented on tests/test_scene_rendering/test_caching_relalted.py
> +from ..utils.video_tester import *
It would be nice to get rid of wildcard imports whenever possible.

```suggestion
from ..utils.video_tester import video_comparison
```

2020-09-24 18:27 UTC, huguesdevimeux commented
Should be good now :D

2020-09-24 18:53 UTC, behackl approved these changes
Now it's good! :-)

2020-09-29 12:03 UTC, kilacoda approved these changes

2020-09-29 12:34 UTC, merged