Fix docs for `Variable` and remove some unused imports
ManimCommunity/manim pull request #520
Opened 2020-10-06 18:02 UTC by nilaybhatia

## List of Changes
- Remove some imports which are not used at all in `manim/mobject/numbers.py`
- Add a new line in example section for `Variable` in order for the examples to correctly render.
- Add some more classes to docs which were supported but not documented.

## Motivation
The example section of [`Variable`](https://manimce.readthedocs.io/en/latest/reference/manim.mobject.numbers.Variable.html#manim.mobject.numbers.Variable) in the current docs does not render properly.

## Acknowledgement
- [ ] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

2020-10-06 18:29 UTC, behackl requested changes
Looks good to me, two (actually one) minor issue found, please consider my suggestions.

2020-10-06 18:29 UTC, behackl commented on manim/mobject/numbers.py
> +    label : Union[:class:`str`, :class:`~.Tex`, :class:`~.MathTex`, :class:`Text`, :class:`TexSymbol`, :class:`SingleStringMathTex`, :class:`MathTexFromPresetString`]
From a user point of view, I find it confusing to list all subclasses of `SingleStringMathTex`, but this is maybe a discussion for another day. Anyhow: the references to the classes are not set correctly (you can check: they are not rendered as links right now).

```suggestion
    label : Union[:class:`str`, :class:`~.Tex`, :class:`~.MathTex`, :class:`~.Text`, :class:`~.TexSymbol`, :class:`~.SingleStringMathTex`, :class:`~.MathTexFromPresetString`]
```

2020-10-06 18:29 UTC, behackl commented on manim/mobject/numbers.py
> +    label : Union[:class:`str`, :class:`~.Tex`, :class:`~.MathTex`, :class:`Text`, :class:`TexSymbol`, :class:`SingleStringMathTex`, :class:`MathTexFromPresetString`]
```suggestion
    label : Union[:class:`str`, :class:`~.Tex`, :class:`~.MathTex`, :class:`~.Text`, :class:`~.TexSymbol`, :class:`~.SingleStringMathTex`, :class:`~.MathTexFromPresetString`]
```

2020-10-07 13:56 UTC, behackl approved these changes

2020-10-07 14:01 UTC, leotrs approved these changes

2020-10-07 14:01 UTC, merged