graph_scene: correct placement of labels
ManimCommunity/manim pull request #661
Opened 2020-11-01 10:29 UTC by PhilippImhof

Currently, when users use `add_end` or `add_start` in order to lengthen the axes a bit before/after the last tick, the labels may be misplaced, especially when using arrow tips. This PR fixes the problem.

## List of Changes
- For the x axis, do not use axis tip or ticks to determine where to put the label. Instead, use `get_corner`.
- For the y axis, specify `aligned_edge` when using `next_to`, i.e. if for any reason someone wants the label to be below the y axis, it should be aligned w.r.t. its top edge.

## Motivation

I just don't like misplaced axis labels :) 

## Testing Status
Tested locally with several combinations.

## Acknowledgement
- [X] I have read the [Contributing Guidelines](https://github.com/ManimCommunity/manim/wiki/Documentation-guidelines-(WIP))

2020-11-01 10:43 UTC, PhilippImhof commented
My bad, I forgot to recreate the reference data for the test. Will do so ASAP
![Figure_1](https://user-images.githubusercontent.com/52650214/97800670-5c2a7f00-1c37-11eb-8f44-80adf1250ba2.png)

2020-11-01 14:54 UTC, leotrs reviewed
This LGTM. I know you fixed an old test, but would you be able to add a new one so we don't regress on this? One that directly calls add_end() for example

2020-11-01 14:55 UTC, PhilippImhof commented
Not quite sure I understand. You mean add a test that makes use of the `add_start` and/or `add_end` functionality?

2020-11-01 14:56 UTC, leotrs commented
Yes

2020-11-01 15:39 UTC, PhilippImhof commented
Done. I came across some strange behavior (not related to my changes though) that I will have to look at more in depth. Basically, the label is sometimes put at the wrong place, e.g. when there is "not enough space" above the y axis. I will open a separate issue for that, providing more details.

2020-11-01 16:51 UTC, leotrs requested changes

2020-11-01 16:51 UTC, leotrs commented on tests/test_graphical_units/test_axes.py
> +
```suggestion
```

2020-11-01 16:51 UTC, leotrs commented on tests/test_graphical_units/test_axes.py
> +# set_test_scene(AxesTest, "graph")
```suggestion
```

2020-11-02 00:45 UTC, leotrs reviewed
I see you've added or modified AxesTest and PlotFunctions, but I don't see which one of them actually calls the functions add_start or add_end? :thinking: Am I missing anything?

2020-11-02 06:54 UTC, PhilippImhof commented
I'd say `tests/test_graphical_units/test_axes.py` has that on L15-16 and L20-21. :)

2020-11-02 07:40 UTC, PhilippImhof commented
After having digged deeper, I suggest to fix #663 directly with this PR as soon as we have a consensus on what behavior to adopt.

2020-11-02 14:21 UTC, leotrs approved these changes

2020-11-02 21:30 UTC, cobordism approved these changes
looks fine to me.

2020-11-03 12:19 UTC, merged