Added flowchart for Docs overview
ManimCommunity/manim pull request #828
Opened 2020-12-04 02:10 UTC by kolibril13

This flowchart, made by @leotrs provides an overview of what and where to find things in the docs.

In the flowchart there was the option "embed as HTML".
I will try this first, but if that does not work, we can include this as an png.

2020-12-04 05:40 UTC, naveen521kk requested changes

2020-12-04 05:40 UTC, naveen521kk commented on docs/source/contributing.rst
> +<div class="mxgraph" style="max-width:100%;border:1px solid transparent;" data-mxgraph="{&quot;highlight&quot;:&quot;#0000ff&quot;,&quot;nav&quot;:true,&quot;resize&quot;:true,&quot;toolbar&quot;:&qu
Please don't use your drive url. Instead add the png file to source tree.

2020-12-04 09:44 UTC, kolibril13 commented
To clarify why I chose this approach:
* As pngs have mostly a size of ~Mb , this HTML approach produces less memory in the repo (Especially when pngs are altered, this quickly goes up) 
* This is easier to maintain: If we want to change something in this flowchart, we can simply go to the flowchart and edit it on app.diagrams.net (probably we should find a way that this link is only accessible for community devs.)
* On the website, this just looks *delightful*: There is a nice increase button, you can zoom, and shift around etc.

2020-12-05 15:38 UTC, leotrs commented
Looks great! I just tried editing the flowchart via the URL you linked and it shows immediately :+1:

2020-12-05 15:38 UTC, leotrs approved these changes

2020-12-05 15:56 UTC, naveen521kk approved these changes
LGTM! Also it works.

2020-12-05 15:56 UTC, merged

2021-01-14 16:30 UTC, kolibril13 commented
Links to the diagrams:
https://app.diagrams.net/#G1aKyJTloYB97IhrzwqEENOu-WQyuVWMjM
https://app.diagrams.net/#G1WYVKKoRbXrumHEcyQKQ9s1yCnBvfU2Ui