Small fixes to docstrings. Tiny cleanups. Comment out (for now) an unused function.
ManimCommunity/manim pull request #834
Opened 2020-12-05 18:08 UTC by cobordism

tex_mobject.py - better docstring for remove_stray_braces
mobject.py - fix: "depth" is index 2, not 1
mobject.py - docstring comment correction
mobject.py - digest_mobject_attrs is never used (thankfully)
tex_mobject.py - don't set partent class attributes in child init()

2020-12-05 18:41 UTC, leotrs requested changes

2020-12-05 18:41 UTC, leotrs commented on manim/mobject/mobject.py
> +    #     return self
Issue: please don't add commented out code to the codebase. If you mean to delete the code, just delete it :slightly_smiling_face: 
```suggestion
```

2020-12-05 18:41 UTC, leotrs commented on manim/mobject/mobject.py
> +        self.target = None  # Prevent unbounded linear recursion
Praise: THANK YOU. I saw this before and it bothered me

2020-12-11 11:53 UTC, behackl reviewed
This LGTM, please consider the two suggestions I've made. (I also pushed a commit running black, I hope you don't mind.)

2020-12-11 11:53 UTC, behackl commented on manim/mobject/mobject.py
> +        """
Oneline descriptions should be a bit shorter, technical explanations can come afterwards.

```suggestion
        """Adds (or moves) all passed mobjects to the back of the scene.
        
        .. note::

            Technically, this is done by adding (or moving) the mobjects to
            the head of ``self.submobjects``. The head of this list is rendered
            first, which places the corresponding mobjects behind the
            subsequent list members.
        """
```

2020-12-11 11:53 UTC, behackl commented on manim/mobject/svg/tex_mobject.py
> +        tex code are spread over multiple agruments eg. MathTex(r"e^{i", "\tau} =1")
Similar to above.

```suggestion
        r"""
        Makes :class:`~.MathTex` resilient to unmatched braces.
        
        This is important when the braces in the TeX code are spread over 
        multiple arguments as in, e.g., ``MathTex(r"e^{i", r"\tau} = 1")``.
```

2020-12-11 13:17 UTC, leotrs approved these changes

2020-12-11 13:17 UTC, leotrs commented
Took the liberty of adding @behackl 's changes - one more review and we can merge this

2020-12-11 13:19 UTC, behackl approved these changes
In that case: let's merge after the tests pass.

2020-12-11 14:16 UTC, merged