Multipartite graph column layout
ManimCommunity/manim pull request #916
Opened 2021-01-09 10:14 UTC by noamzaks

## Motivation
Add the multipartite column layout for graphs, e.g.

https://user-images.githubusercontent.com/63877260/104088910-e106ca00-5272-11eb-98e9-73ef5f301651.mp4

## Overview / Explanation for Changes
Added the option for networkx multipartite automatic layout (similar to planar, spectral, etc.)

## Oneline Summary of Changes

```
- Added new layout 'partite' for Graph mobject (:pr:`PR NUMBER HERE`)
```

## Testing Status
The following code
```python
from manim import *
import networkx as nx

G = nx.Graph()
G.add_nodes_from([0, 1, 2, 3], bipartite=0)
G.add_nodes_from([4, 5, 6, 7], bipartite=1)
G.add_edges_from([(0, 4), (0, 6), (1, 6), (2, 5), (3, 7)])

T = nx.Graph()
T.add_nodes_from([0, 1, 2, 3, 4, 5, 6, 7])
T.add_edges_from([(0, 2), (0, 3), (3, 6), (1, 2), (5, 7)])

class Test(Scene):
    def construct(self):
        graph = Graph(list(G.nodes), list(G.edges), layout="partite", partitions=[
                      [0, 1, 2, 3]])
        self.play(ShowCreation(graph))
        self.play(FadeOut(graph))

        graph = Graph(list(T.nodes), list(T.edges), layout="partite",
                      partitions=[[0, 1], [2, 3], [4, 5], [6, 7]])
        self.play(ShowCreation(graph))
        self.play(FadeOut(graph))

        # Doesn't specify the remaining side
        graph = Graph(list(T.nodes), list(T.edges), layout="partite",
                      partitions=[[0, 1], [2, 3], [4, 5]])
        self.play(ShowCreation(graph))
        self.play(FadeOut(graph))

        # Fails (should it put everything on one side? seems worthless...)
        # graph = Graph(list(T.nodes), list(T.edges), layout="partite")
        # Also fails
        # graph = Graph(list(T.nodes), list(T.edges),
        #               layout="partite", partitions=[])
        graph = Graph(list(T.nodes), list(T.edges),
                      layout="partite", partitions=[[0, 1]])
        self.play(ShowCreation(graph))
        self.play(FadeOut(graph))
```
outputs the following video

https://user-images.githubusercontent.com/63877260/104088926-098ec400-5273-11eb-9a33-c0796d539eea.mp4

## Further Comments
Also discussed in #913

## Acknowledgements
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

2021-01-09 11:23 UTC, behackl requested changes
Thank you for your contribution, this is great! I have two minor suggestions (see below) and one minor change request:

In https://github.com/ManimCommunity/manim/pull/916/files#diff-8cf05d12c38d38c8c9c88bcd871ec3aff4f744fe3a6817044ba3524ddf6b6ff4R52 (the description of the `layout` parameter in the docstring), could you please also add `partite` to the list of possible values of `layout`?

2021-01-09 11:23 UTC, behackl commented on manim/mobject/graph.py
> +        import networkx as nx
The example requires a newline between the head of the directive and the code block.

```suggestion

        import networkx as nx
```

2021-01-09 11:23 UTC, behackl commented on manim/mobject/graph.py
> +        will be put into another column.
I feel that we can be a bit more explicit in this note:

```suggestion
        All vertices in your graph which are not listed in any of the partitions
        are collected in their own partition and rendered in the rightmost column.
```

2021-01-09 12:23 UTC, behackl approved these changes
LGTM, thank you!

2021-01-11 08:10 UTC, kolibril13 approved these changes

2021-01-12 10:04 UTC, merged