set_fill() and set_stroke() make opacity 1 if was 0
ManimCommunity/manim pull request #956
Opened 2021-01-25 06:25 UTC by sparshg

## Motivation

set_fill() and set_stroke() should set their opacities 1 if it was 0, because when I first tried to set_fill(), it would not show and I got really confused until I checked the code which doesn't change the opacity if not mentioned... which is good but there is no point to set colors if the thing is already totally transparent.
## Overview / Explanation for Changes
When you set_fill(BLUE), it will change the opacity to 1 it it was previously transparent, which is more intuitive and reasonable.
Also I added some docs to few methods

## Oneline Summary of Changes

```
- update_rgbas_array() will set the opacity to 1 if it was 0 ... / Added some things docs... / ... (:pr:`PR NUMBER HERE`)
```

## Acknowledgements
- [ ] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)

## Reviewer Checklist
- [ ] Newly added functions/classes are either private or have a docstring
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
- [ ] The oneline summary has been included [in the wiki](https://github.com/ManimCommunity/manim/wiki/Changelog-for-next-release)

2021-01-25 07:01 UTC, sparshg commented
okayy I guess I will have to do some changes

2021-01-25 18:10 UTC, huguesdevimeux submitted a review, later dismissed
SGTM! 

Do you think you could add a graphical unit test for that ? Everything is explained there. 
https://github.com/ManimCommunity/manim/wiki/Testing

If you're not sure or you don't understand, please tell !

2021-01-25 18:14 UTC, huguesdevimeux commented
EDIT : I was too fast and didn't see the failing tests. 

  I believe failing tests are normal as IIRC the failing test is the one testing set_sheen. Then, you'll have to rewrite the failing test and to regenerate the control data. cf [wiki](https://github.com/ManimCommunity/manim/wiki/Testing). 

If you're not sure, feel free to tell and I can do it for you.

2021-01-25 20:06 UTC, sparshg commented
Yeah I am doing some changes and will comment explaining the things and adding some docs

2021-01-25 21:15 UTC, sparshg commented
Actually whats failing is the set_color() thing. According to me these three functions, set_color(), set_stroke(), set_fill() seem to overlap and make confusion.

For example I make a Square().set_color(BLUE). Now, according to code set_color() sets both fill + stroke. But you only see that the stroke gets changed, (because the fill is transparent by default... I mean if a person doesn't check the code how can you know that set_color doesn't just fill the outlines.... and then set_fill seems to do nothing because fill is transparent.. so you have to use opacity parameter which is again confusing if you don't check the code... its so unintuitive to me).

Similarly, set_fill() is used to fill the object and make it opaque if it was transparent to avoid confusion and avoiding the need to do set_color(BLUE).set_opacity(1) or doing set_fill(BLUE, opacity=1). Added similar thing to set_stroke()

**Added explanation to docs too.**

**In the failing test**
set_color() is used to make the outlines RED in output. But my change will make the square fill also red. If one wants to set the stroke, then they should use set_stroke(), this will avoid such confusions. So its intended change.

2021-01-26 18:00 UTC, huguesdevimeux commented
@sparshg I just fixed and added some new tests, so you don't have to worry about it. 

If you're good, then I'll approve!

2021-01-26 19:12 UTC, sparshg commented
@hugesdevimeux looks good imo

2021-01-26 19:42 UTC, huguesdevimeux approved these changes

2021-01-26 20:08 UTC, behackl requested changes
The changes in the code look good to me; the documentation needs some more work though. I've added a bunch of suggestions.

2021-01-26 20:08 UTC, behackl commented on manim/mobject/types/vectorized_mobject.py
> +        """Changes the direction of the sheen applied, use set_sheen() to apply
```suggestion
        """Changes the direction of the applied sheen.
```

2021-01-26 20:08 UTC, behackl commented on manim/mobject/types/vectorized_mobject.py
> +        --------
```suggestion
        ----------
```

2021-01-26 20:08 UTC, behackl commented on manim/mobject/types/vectorized_mobject.py
> +        :meth:`set_sheen`
```suggestion
        :meth:`~.VMobject.set_sheen`
```

2021-01-26 20:08 UTC, behackl commented on manim/mobject/types/vectorized_mobject.py
> +        """Applies a gradient from a direction to introduce a soft lustre.
```suggestion
        """Applies a color gradient from a direction.
```

2021-01-26 20:08 UTC, behackl commented on manim/mobject/types/vectorized_mobject.py
> +            if positive the gradient starts from white (to current color)
```suggestion
        factor : :class:`float`
            The extent of lustre/gradient to apply. If negative, the gradient
            starts from black, if positive the gradient starts from white and
            changes to the current color.
```

2021-01-26 20:08 UTC, behackl commented on manim/mobject/types/vectorized_mobject.py
> +            Direction from where the gradient is applied
```suggestion
            Direction from where the gradient is applied.
```

2021-01-26 20:08 UTC, behackl commented on manim/mobject/types/vectorized_mobject.py
> +        ---------
```suggestion
        --------
```

2021-01-26 20:09 UTC, behackl commented
... and thank you for your contribution, of course! It is much appreciated!

2021-01-27 05:13 UTC, sparshg commented on manim/mobject/types/vectorized_mobject.py
> +    def set_color_only(self, color, family=True):
idk if there is a better solution, for FadeToColor animation to work as before, the opacities of fill and color should remain unaltered. (btw I fixed this function, forgot to remove the testing code)

2021-01-27 11:06 UTC, sparshg commented
I guess everything is fixed now, sorry for so many commits lol that was my first pull request...

2021-02-08 13:23 UTC, huguesdevimeux approved these changes
Tests SGTM. 

Waiting for @behackl review and we can merge!

2021-02-10 16:42 UTC, sparshg commented
The conflict arose due to my own PR #1003, should try to fix

2021-02-25 17:33 UTC, eulertour commented
Color and opacity shouldn't be coupled, the user should call set_stroke/fill_opacity if they want opacity to change.

2021-02-25 18:40 UTC, sparshg commented
@eulertour I thought that setting opacity with color would make sense because set_color() calls set_fill() and set_stroke()
So set_color(opacity) now calls set_fill(opacity), set_stroke(opacity)
And for that purpose I did create set_color_only() function which doesn't set opacity

2021-02-25 18:42 UTC, eulertour commented
Well setting color without the opacity should be the default for a method called set_color. set_color should still call set_fill and set_stroke to change the color for each of them, just not the opacity.

2021-02-25 18:48 UTC, sparshg commented
wait, but opacity parameter is optional for set_color() soo without opacity it works the same by just calling set_fill() and set_stroke().

2021-02-25 18:50 UTC, eulertour commented
If calling set_color without opacity doesn't change the opacity then that's fine, but the description says it'll set opacity to 1 if opacity isn't passed.

If the user specifies an opacity in set_color then it makes sense to update opacity of course.

2021-02-25 18:55 UTC, sparshg commented
yeah because I changed set_fill() and set_stroke() to do that and set_color() calls those 2 so thats why opacity is changing.
So you mean set_color() should not do this and retain original behaviour (which set_color_only does)

2021-02-25 18:57 UTC, eulertour commented
Yes, set_color should only affect color by default.

2021-02-25 19:28 UTC, sparshg commented
@eulertour ok as you said, set_fill and set_stroke will change opacity to 1 if 0 and nothing passed
but set_color() works like before with an optional opacity parameter

2021-02-25 19:35 UTC, eulertour commented
Nothing should set opacity to 1 if it's 0 by default, opacity should only change if the user calls for it to be changed.

2021-02-25 19:40 UTC, sparshg commented
uhh then what was the point of this PR lol, this PR sets fill/stroke color to 1 if it was 0
like Circle().set_fill(BLUE) and Circle.set_stroke(BLUE) currently have same output coz of transparent fill which this change fixes.... Other things are same as before

2021-02-25 19:44 UTC, eulertour commented
I don't think this change should be made at all, it presupposes too much about what the user wants to do.

2021-02-25 19:51 UTC, sparshg commented
ok whatever, I just wanted this change coz when I started using manim, I spent ages knowing that the default fill opacity of shapes is transparent, and setting color/fill doesn't do anything lol. I still think these 3 methods should change opacity to 1 if was 0 and nothing is mentioned.

2021-02-25 19:55 UTC, eulertour commented
> when I started using manim, setting color/fill doesn't do anything

That shouldn't happen, if you set the color when the stroke opacity isn't 0 that should be visible.

2021-02-25 20:02 UTC, sparshg commented
I meant this: This won't do anything
```py
circle = Circle()
self.add(circle)
self.play(circle.animate.set_fill(BLUE))
```
Then I tried using set_stroke and set_color which changed outline only... Soo I had to watch some tutorial to clear the confusion

2021-02-25 20:11 UTC, eulertour commented
Yeah, you'd have to also update the fill opacity to see that, since the attributes aren't coupled.

2021-02-25 20:12 UTC, PhilippImhof commented
I feel there is some dilemma here. On one hand, `set_fill` should not mess with the opacity that the user might have set earlier. On the other hand, 
```python
circle = Circle()
self.add(circle)
self.play(circle.animate.set_fill(BLUE))
```
should definitely result in that circle being blue...

2021-02-25 20:20 UTC, eulertour commented
I disagree, the method should just do what the name indicates.

You made a set_color_only() method earlier, so why not add a set_opaque_color() or set_color_with_with_opacity() method?

2021-02-25 20:30 UTC, sparshg commented
or.. why don't we just change the default fill value to opaque instead like every application does... This way we won't have to do these changes and if one wants to make a shape fill transparent they can do Circle(fill_opacity=0) or Circle().set_fill(opacity=0).

2021-02-25 20:38 UTC, eulertour commented
The shapes with the fill are generally more useful for illustrating concepts than ones with fill, so that's why it's 0 be default.

2021-02-25 20:39 UTC, PhilippImhof commented
> I disagree, the method should just do what the name indicates.

Absolutely. But it should do it in a reasonable way. If the function sets the fill color, but leaves it fully transparent, that's most certainly not what one expects. 

If the opacity is currently 0, it could be set to 1, but an optional parameter could be set to inhibit this behaviour for those who would really want to set a fill color without it being visible.

2021-02-25 20:41 UTC, sparshg commented
>  but an optional parameter could be set to inhibit this behaviour for those who would really want to set a fill color without it being visible.

That can already be done by just saying set_fill(opacity=0) though

2021-02-25 20:47 UTC, PhilippImhof commented
> That can already be done by just saying set_fill(opacity=0) though

Yes, but I thought something like `do_not_touch_my_very_well_chosen_opacity` would make the idea clearer. The user might not want to restate their value.

2021-02-25 20:47 UTC, sparshg commented
imo 0 default opacity doesn't make sense, it should be "None" instead of 0, and now we can check if set_fill() is called and `current opacity == None and passed opacity == None` then set opacity to 1.. so this might be another solution

2021-02-25 20:50 UTC, sparshg commented
> Yes, but I thought something like `do_not_touch_my_very_well_chosen_opacity` would make the idea clearer. The user might not want to restate their value.

If you think, this situation will never arise...
The change will only alter opacity if opacity is 0 and set_fill is called... (why would you call set_fill with 0 opacity -_-)
or if opacity is 0 and set_stroke is called... (why would you call set_stroke with 0 opacity -_-)

I don't see a reason to deny these changes actually

2021-02-25 20:57 UTC, PhilippImhof commented
> What I described before is the most reasonable way. 

Setting the fill color without it being visible seems all but reasonable to me, but that is just personal.

2021-02-25 21:01 UTC, eulertour commented
The fill color is only an attribute. If you add or move points on a mobject with 0 opacity, there's no reason for that to update the opacity too.

If you want an animation to behave that way then that would make more sense since their primary purpose is to be played, but attributes are just for storing data.

2021-02-25 21:10 UTC, sparshg commented
That code was just for example... the problem is simply that this produces a red outlined circle:
'''py
circle=Circle()
#do stuff
circle.set_fill(BLUE)
self.wait()
'''

2021-02-25 21:14 UTC, eulertour commented
It looks like it wouldn't produce anything since the circle wasn't added to the scene, but in any case that's expected behavior since the default fill opacity is 0.

2021-02-25 21:51 UTC, closed without merging